Khan/jenkins-jobs

- sync-captions.sh
Testing for the Bofa videos, will revert back to original after success.
> Run only some youtube ids for the captions job

- sync-captions.sh
After running tests on Bofa and CS videos, turning off the special casing.
> Going back to original code

- jobs/qa-metrics.groovy
Differential Revision: https://phabricator.khanacademy.org/D67999
> add qa metrics groovy

- jobs/deploy-znd.groovy
I want to direct ZND messaging to a slack thread, so I'm updating the job to support that.
I already checked the commands that it calls and they all support `--slack-thread` already.
I'll be running a ZND with a thread ID and checking that it reports where it should.
> Add slack thread to deploy znd

- vars/notify.groovy
At this point, the console logs are not very useful for figuring out
what's going on with a jenkins job, since so many things are happening
in parallel.  In practice, I find looking at the pipeline steps to be
the way to figure out what went wrong.
In this commit, I change the generic "job failed" message to point
people to the pipeline-steps page.  I also made it so we no longer
show the tail of the logs, since the heuristic "if there was an error
it's probably near the bottom" no longer applies very often.
Issue: https://khanacademy.slack.com/archives/C02NMB1R5/p1637011218262600
`groovy vars/notify.groovy`
But mostly I'll deploy this and then run a webapp-test job and make
sure there are no groovy errors.
> Try to give more informative messages when jenkins jobs fail.

- weekly-maintenance.sh
We forgot to do this, and now tens of thousands of obsolete graphql
schema files are cluttering up our gcs.  Let's clean the directory up
every week.
I don't actually know how often old schema files are used, so I'm
pretty conservative: I keep the last 2 months' worth of schema files.
To be extra safe, I also keep the last 50 (not including znds), so if
we ever get to a world where we're going for months without updating
the schema files, we'll still keep them around.
Issue: https://khanacademy.atlassian.net/browse/INFRA-6062
I ran the commands manually and they seemed to delete good things.
> Clean old graphql-gateway files from gcs.

- weekly-maintenance.sh
I updated the job to modify all of them, but forgot to modify the
commit line when I did it.  Oops.
Issue: none
Ran the command manually and it worked
> [🔥AUDIT🔥] Commit *all* the yarn.lock files, not just the top-level one.

- jobs/build-webapp.groovy
> Pre-computing the query-plans for the latest safelist queries when deploying.

- .github/CODEOWNERS
Issue: https://khanacademy.atlassian.net/browse/INFRA-7643
Test plan:
- fingers crossed
> INFRA-7643 Track changes going into jenkins

- jobs/deploy-znd.groovy
I cut-and-paste from build-webapp, when there are actually slight
differences.
Issue: https://jenkins.khanacademy.org/job/deploy/job/deploy-znd/4674/flowGraphTable/
groovy jobs/deploy-znd.groovy
> [🔥AUDIT🔥] Fix a typo in 1a9d5beda5e079c93, when uploading queryplan for znd's.

- jobs/update-i18n-lite-videos.groovy
This PR updates the update-i18n-lite-videos job to use the new Go script
added in github.com/Khan/webapp#4443.
Issue: https://khanacademy.atlassian.net/browse/INFRA-7693
Fingers crossed.
> Update the update-i18n-lite-videos job to use the new Go script

- build_current_sqlite.sh
It's failed the last few days, seemingly because it wasn't waiting
long enough for the queryplanner to start up (it can take a while).
This change uses polling instead of just an arbitrary sleep, so
hopefully it will work better.
Issue: https://jenkins.khanacademy.org/job/misc/job/build-current-sqlite/1287
Fingers crossed, will try running the job in prod.
> [🔥AUDIT🔥] Try to fix build_current_sqlite by being smarter about waiting for services.

- vars/withVirtualenv.groovy
Revert "[🔥AUDIT🔥] Add login_v3: false to the keeper-config. (#41)"
Issue: none
> [🔥AUDIT🔥] Revert our hack to unset login_v3 now that it's unset in the base image

- jobs/build-translation-pipeline-image.groovy
- jobs/update-translation-pipeline.groovy
After waiting for over an hour for `make push` to finish I started to reevaluate my life choices.
Having this run somewhere else seems like a good change to start with.
Test Plan:
- I don't know what I'm doing. Is this it?
> Add a jenkins job to build the translation-pipeline image

- jobs/e2e-test-cypress.groovy
Issue: FEI-4628
Run job with Replay
> Configure lambdatest run arguments

- jobs/e2e-test-cypress.groovy
> [🔥AUDIT🔥] Allow multiple LambdaTest runs to execute concurrently

- jobs/deploy-znd.groovy
This code is very out-of-date and no one is using it. I'm deleting it from webapp and so may as well make sure the job doesn't refer to it either.
Issue: FEI-4651
Keep calm and carry on
> Remove phabricator fixture support

- jobs/e2e-test-cypress.groovy
> Reverse back retries changes

- jobs/find-failing-taskqueue-tasks.groovy
It was missing the secrets it needed to do so.
Issue: none
Ran this manually on jenkins with successful slack output:
https://khanacademy.slack.com/archives/C3UDL9QN7/p1661746951845259
> [🔥AUDIT🔥] Get the job actually posting to slack again.

- jobs/deploy-znd.groovy
These flags haven't done anything for a while now.
Issue: none
> Get rid of some unused flags on `deploy-znd.groovy`.

- jobs/build-webapp.groovy
In a previous PR https://github.com/Khan/jenkins-jobs/pull/87 I added some new functionality to create traffic tags in cloud run.  Somehow I had a bad merge and deployed groovy code that is wrong; Im missing a comma.
So Im adding that comma here!
Issue: https://khanacademy.atlassian.net/browse/INFRA-8963
Deploy something and verify it works!
> [🔥AUDIT🔥] Added missing comma causing script to fail

- jobs/e2e-test.groovy
- jobs/firstinqueue-priming.groovy
This is a rollout of the Cypress e2e tests. This is the first
step in the rollout, which is to switch the e2e tests to run on the
Cypress infrastructure instead of the Python-Selenium infra.
The next step will be to remove the `e2e-cypress-*` jobs that were
created while we tested this integration in parallel with the
Python-Selenium infra.
Issue: FEI-4888
Jenkins via the "Replay" button.
NOTE: I created two separate Replay jobs to verify that `first` and
`second` e2e tests pass.
1. first-smoke-test: https://jenkins.khanacademy.org/job/deploy/job/e2e-test/47341/console
2. second-smoke-test: https://jenkins.khanacademy.org/job/deploy/job/e2e-test/47343/console
it passes in Jenkins via the "Replay" button.
https://jenkins.khanacademy.org/job/deploy/job/firstinqueue-priming/3019/console
> FEI-4888.1: Switch to Cypress for e2e tests

- jobs/update-ownership-data.groovy
Oops!
Issue: https://jenkins.khanacademy.org/job/misc/job/update-ownership-data/1461/execution/node/137/log/
Will run the job again
> [🔥AUDIT🔥] Get the right path for runpytests.sh.

- jobs/go-codecoverage.groovy
The go-codecoverage jenkins job is currently set up to run groovy in
config.xml, not in go-codecoveage.groovy.  This is the first step to
changing it to use the latter: getting the groovy file to match the
current contents of config.xml, taken from
https://jenkins.khanacademy.org/job/misc/job/go-codecoverage/configure
Issue: none
None
> [🔥AUDIT🔥] Update the groovy file to match what we're actually running.

- jobs/webapp-test.groovy
- vars/buildmaster.groovy
- vars/notify.groovy
- vars/onMaster.groovy
- vars/onWorker.groovy
We are putting the parallel-deploys project on hold so let's revert
this change, which adds complexity and latency.
Issue: INFRA-9290
none
> Revert "INFRA-9290 Log High level jenkins actions to GOOGL"

- jobs/e2e-test.groovy
Now that we're on TS, we need to use that, instead!
We'll be running the Cypress tests and confirming that it works.
> [🔥AUDIT🔥] Switch to .ts for the result reporting script.

- jobs/build-webapp.groovy
prime_query_plan_cache can log some scary-looking errors that are, in
fact, harmless.  Give some explanatory text in the hopes of calming
some of that scariness.
Issue: https://khanacademy.slack.com/archives/C096UP7D0/p1693421424702009
> [🔥AUDIT🔥] Log some explanatory text about error messages when deploying.

- jobs/update-ownership-data.groovy
Issue: https://jenkins.khanacademy.org/job/misc/job/update-ownership-data/1589/execution/node/155/log/
Will run manually.  AGain.
> [🔥AUDIT🔥] Gah, runtests.sh lives in tools/, not testing/.

- vars/notify.groovy
Issue: https://jenkins.khanacademy.org/job/deploy/job/merge-branches/212307/console
> [🔥AUDIT🔥] Add a paren, oops

- jobs/build-webapp.groovy
- vars/withSecrets.groovy
We need the graphql-safelist-secret to upload to graphql.
I also rewrote withSecrets in a way that should not leak the secrets
in the jenkins logs anymore.
Issue: INFRA-XXXX
> [🔥AUDIT🔥] Add back in secrets in a place where they're needed.

- jobs/deploy-fastly.groovy
Issue: none
Will run on jenkins
> [🔥AUDIT🔥] Oops I added a `{` in my last commit but forgot to add the `}`

- vars/withSecrets.groovy
I set up the right secrets dir, but suffered from copy-pasta!
Issue: None
Will try a fastly deploy
> [🔥AUDIT🔥] I was not setting ALERTLIB_SECRETS_DIR to the right value.

- vars/withSecrets.groovy
So I need to use the `-r` flag to `rm`.
Y'know?
Issue: none
will run a jenkins test job
> [🔥AUDIT🔥] I'm deleting directories, y'know?

- vars/withSecrets.groovy
> [🔥AUDIT🔥] Make our temp secrets.py files even more atomic.

- vars/withSecrets.groovy
`exec(['echo', '$$'])` just returns `$$`.  I have to use `sh` to get
the shell interpoloation to return an actual value.
Issue: https://jenkins.khanacademy.org/job/deploy/job/deploy-webapp/16346/flowGraphTable/
Will try deploying
> [🔥AUDIT🔥] Fix uniqueId to actually return a number.

- vars/withSecrets.groovy
Issue: https://jenkins.khanacademy.org/job/deploy/job/deploy-webapp/16348/console
Will try a deploy
> [🔥AUDIT🔥] Ugh, a typo in the `mv` command.

- .github/CODEOWNERS
We have transitioned ownership of this code to infra-platform so Im reflecting that in the github code owners so that the correct group of folks get code reviews.
Issue: https://khanacademy.slack.com/archives/C01120CNCS0/p1698247174759139
Wait for a PR - after this one lands - and verify that platform infra is added as reviewer.
> [🔥AUDIT🔥] Updating owner to infra-platform for code reviewing purposes

- jobs/webapp-maintenance.groovy
That way, you can manually run just a subset of the maintenance tasks.
Issue: none
groovy jobs/webapp-maintenance.groovy
> [🔥AUDIT🔥] Allow the weekly-maintenance job to specify what tasks to run.

- jobs/demo-district-update-pass.groovy
Summary:
This is a cron job scheduled to run monthly Cypress/Python scripts for updating demo passwords in the PL Demo District.
Automate monthly change for PL sandbox account passwords.
Issue: DIST-4092
Successfully ran the script manually on the Jenkins server.
> Description: Automate monthly change for PL sandbox account passwords Issue: https://khanacademy.atlassian.net/browse/DIST-4092

- jobs/delete-version.groovy
We're seeing timeouts.
Issue: https://jenkins.khanacademy.org/job/deploy/job/delete-version/146585/consoleFull
> [🔥AUDIT🔥] Give the job a bit more time to sync webapp.

- weekly-maintenance-jobs.sh
It doesn't exist!  We only use yarn in subdirs now.
Issue: https://jenkins.khanacademy.org/job/misc/job/webapp-maintenance/287/execution/node/1310/log/
> [🔥AUDIT🔥] Do not try to check in the top-level yarn.lock file anymore.

- jobs/webapp-maintenance.groovy
- vars/withVirtualenv.groovy
Issue: https://jenkins.khanacademy.org/job/deploy/job/webapp-test/215659/execution/node/1414/log/
> [🔥AUDIT🔥] Oops I got the path wrong where the deploy virtualenv lives!

- vars/withVirtualenv.groovy
I forced the creation of the virtual env for python in the jobs to help me determine if that would make python happy creating the virtual env.  It does. But clearly that is not what we want to do.  So Im reverting while I figure out a sustainable solution.
Issue: https://khanacademy.slack.com/archives/C096UP7D0/p1707318372614619
Should be back to what we were before.  Im just undoing the change.
> [🔥AUDIT🔥] Reverting forcing make deps in deploy scripts

- jobs/build-webapp.groovy
- jobs/delete-version.groovy
- jobs/deploy-webapp.groovy
- jobs/deploy-znd.groovy
- jobs/emergency-rollback.groovy
- jobs/find-failing-taskqueue-tasks.groovy
- jobs/firstinqueue-priming.groovy
- jobs/notify-znd-owners.groovy
- jobs/webapp-test.groovy
- weekly-maintenance.sh
This builds the python2 deps, but we no longer need that, because we
no longer run any python2 code from jenkins!
Issue: https://khanacademy.atlassian.net/browse/INFRA-9771
None
> No longer run `make python_deps`.

- jobs/deploy-fastly.groovy
This just means running our make rules in a different directory, basically.
This has preliminary support for staging, but not yet full support
since we don't have a way to specify a url to use to reach the staging
service.
Issue: https://khanacademy.atlassian.net/browse/INFRA-10309
groovy jobs/deploy-fastly.groovy
> Update deploy-fastly.groovy to support compute@edge.

- jobs/deploy-fastly.groovy
I landed it with some uncalled functions and repeated functionality.
I also landed it when we didn't have a "set-default" option for
compute@edge.  But now we do, so let's fix up the jenkins job.  It's a
lot cleaner now.
Issue: none
Fingers crossed -- will try to run it once it's landed!
> Fix the deploy-fastly script.

- jobs/update-devserver-static-images.groovy
Jira: No Ticket
Ref: https://khanacademy.slack.com/archives/C01120CNCS0/p1736364027808069?thread_ts=1736318103.575939&cid=C01120CNCS0
> fix(devserver/images): update job status target to point to the local-devserver

- jobs/update-devserver-static-images.groovy
> [🔥AUDIT🔥] Fix a comment on why we run the docker job where we do.

- jobs/e2e-test-cycloud.groovy
update e2e-test-cycloud to merge and analyze test results
in conjunction with webapp update: https://github.com/Khan/webapp/pull/29302
Issue: FEI-6124
ran script on test job and the jobs were reporting successfully
> update e2e-test-cycloud to merge and analyze test results

- jobs/e2e-test.groovy
Issue: FEI-6125
Summary:
This PR introduces a Cypress Cloud job (`e2e-test-cycloud.groovy`) that runs in parallel with the existing Lambda e2e-test job.
> Integrate parallel e2e-test-cycloud job with Buildmaster

- jobs/e2e-test.groovy
It's in the misc folder, which is probably not the right place, but
let's fix the script to look in the location where it is.
Issue: https://jenkins.khanacademy.org/job/deploy/job/e2e-test/71303
> [🔥AUDIT🔥] Point the cycloud job to the right location.

- jobs/e2e-test-cycloud.groovy
pr 1 of 2 in preparation to switchover to cypress cloud.
this job shows the updates i've made to `e2e-test-cycloud`
step 2 will be to fully replace `e2e-test` with `e2e-test-cycloud`
Issue: FEI-6153
ran test job
> updated e2e-test-cycloud in preparation for takeover of e2e-test

- jobs/e2e-test.groovy
> [🔥AUDIT🔥] fix errant line of code (from a deleted comment)

- jobs/e2e-test.groovy
fix buildmaster reporting correctly
> [🔥AUDIT🔥] fix buildmaster reporting

- jobs/e2e-test.groovy
added more info to the cypress builds
Issue: FEI-6222
ran script on test job
> added more info to the cypress builds

- jobs/e2e-test.groovy
made a minor adjustment to the branch info we pass to cypress cloud
Issue: FEI-6222
> e2e-test minor adjustment to revision description

- jobs/deploy-fastly.groovy
I added all of them, even those we haven't actually ported to webapp
yet.  That way, I will be able to test them as part of the porting
process.
Issue: https://khanacademy.atlassian.net/browse/INFRA-10540
groovy jobs/deploy-fastly.groovy
> Add all our fastly services to deploy-fastly.groovy.

- jobs/deploy-fastly.groovy
Nothing like running a script to find problems with it!
Issue: https://jenkins.khanacademy.org/job/deploy/job/deploy-fastly/2491/console
Will deploy again
> [🔥AUDIT🔥] Fix another typo when checking for the service-name.

- jobs/e2e-test.groovy
All our jenkins jobs should get secrets from google secrets manager,
rather than using the Jenkins credential-holding functionality, for a
number of reasons:
1) we don't trust jenkins to securely store secrets
2) it's consistent with how we manage all our other secrets
3) it keeps all our secrets in one place, which is important
for auditability and management
4) it's more infrastructure-as-code
This PR changes the one place we were using Jenkins to hold a secret.
After this is live and working, I will delete the credential from
Jenkins via the UI, at
https://jenkins.khanacademy.org/manage/credentials/store/system/domain/_/
Issue: https://khanacademy.slack.com/archives/C01120CNCS0/p1742320942347839
I ran this on Jenkins using "replay"
Subscribers: @somewhatabstract, @Khan/infra-platform
> Fetch the slack token from GSM, not from the jenkins secrets-store.

- jobs/build-webapp.groovy
We are seeing rspack hang at this point:
```
13:47:58  > [3/4] Optimize modules
13:47:58  	[70%] sealing - finish modules
```
https://jenkins.khanacademy.org/job/deploy/job/build-webapp/62204/console
In previous investigations, this was determined to be caused by running
out of memory. Bumping the memory for the node process fixed this for
local dev. We tried bumping this even higher for jenkins but saw little
to no reduction in intermittent hanging builds.
https://github.com/Khan/webapp/pull/31069
When this process hangs, there is no reported failure for jenkins so
this often causes deploys to block the deploy queue without any signal
that it is misbehaving. Let's add a 15 minute timeout so the build will
actually report failure instead of just hanging. …
> Set 15 minute timeout for static build and deploy

- jobs/e2e-test.groovy
revert new gh script
Issue: INFRA-XXXX
> [🔥AUDIT🔥] revert new github script changes

- jobs/e2e-test.groovy
This got changed in webapp and Jenkins is getting tripped up here.
Issue: FEI-XXXX
> [🔥AUDIT🔥] Fix the REPORT_DIR location.

- jobs/build-and-deploy-publish-worker.groovy
This adds a graceful abort so that the #cp-eng slack channel doesn't get a "publish failed" slack message.
This code was written entirely by AI.
Issue: CP-9488
> Added graceful abort for autodeploy feature

- jobs/deploy-znd.groovy
- jobs/merge-branches.groovy
- vars/kaGit.groovy
I did not test the behavior in jobs besides merge-branches. It seems we're not
in the right directory to call git fetch for webapp-test.
https://khanacademy.slack.com/archives/C096UP7D0/p1755629862960059?thread_ts=1755626223.664679&cid=C096UP7D0
Issue: https://khanacademy.atlassian.net/browse/INFRA-10722
webapp-test starts to succeed again.
> [🔥AUDIT🔥] Revert https://github.com/Khan/jenkins-jobs/pull/348
