jobs/e2e-test.groovy, jobs/firstinqueue-priming.groovy
Mobile now use the `develop` branch as their latest code.
Let's update our test to reflect that.
Issue: https://khanacademy.slack.com/archives/CT1CYDM3N/p1619210697012800
[Deploy](https://github.com/Khan/jenkins-jobs#deploy) (i.e. merge!), and rerun failed test.  Confirm that new code from mobile repo
is picked up.
=> Fix jenkins job to sync Mobile's develop branch

jobs/e2e-test.groovy, jobs/webapp-test.groovy
All of our testing jobs end with a required analysis phase. Unfortunately analysis fails if there are no testing reports to analyze. This can be a good thing, since there are legitimately times where test reports might fail to be generated or saved, which should cause the job to fail. However, there are other times we have entered the testing phase, but have no tests to run - either they've been marked as already run elsewhere in the case of e2e tests, or there are just no tests to run for whatever has changed in the case of unit tests. In these scenarios, there are no test reports generated, and that fails analysis, when in reality there is no problem and the stage should complete correctly.
Here we detect this prior to running the tests, then set a variable to let our analysis phase …
=> INFRA-6777 - Update testing jobs to pass if when there are no tests

jobs/make-allcheck.groovy
The make-allcheck rule hasn't been posting to slack for the last
week.  Looking into it, it's because the tests are timing out after 2
hours, which is before they finish running.
I don't know why tests are taking so long now.  Maybe we just have
more of them?  Still, I wouldn't expect all our Go tests to take
longer than all our python tests did.  In any case, I'll just
parallelize `make allcheck` a bit more so it can finish within 2 hours
again.
Issue: none
Figners crossed
=> [🔥AUDIT🔥] Let make-allcheck run on more machines.

weekly-maintenance.sh
Earlier in the week people were experience an in issue with static deploys failing because of 503s.  While investigating the issue I noticed that _manifest.json was no longer in gs://ka-static.  This PR should fix that issue.  I've already deployed a separate webapp PR that manually retries (up to three times) if we encounter any 503s when uploading files to GCS as part of the static deploy process.
Issue: none
```
KA_STATIC_WHITELIST="-e genfiles/topic-icons/icons/ -e ckeditor/ -e live-editor/ -e khan-mathjax-build/ -e /_manifest.json"
gsutil -m ls -r gs://ka-static/ \
| grep . \
| grep -v ':$' \
| grep -v `echo $KA_STATIC_WHITELIST`
```
See the following output:
```
gs://ka-static/_manifest..json
gs://ka-static/_manifest.180201-1131-a47ef9506805.json …
```
=> Exclude _manifest.json from being cleaned up

weekly-maintenance.sh
We've run into a number of issues over the past few months with the cleanup code deleting files we actually need.  This is due to changes to the deploy process that didn't account for the current cleanup process.
Issue: none
- `./weekly-maintenance.sh -l | grep clean_ka_static`, see no hits
=> Disable clean_ka_static

build_current_sqlite.sh
This will hopefully give some clue as to why it's failing.
I am seeing this in the build_current_sqlite job run:
```
20:21:40  + timeout 10h python third_party/frankenserver/dev_appserver.py --application=khan-academy --datastore_path=../current.sqlite --port=9085 --require_indexes=yes --skip_sdk_update_check=yes --automatic_restart=no --admin_port=0 --max_module_instances=1 --log_level=info --host=127.0.0.1 ./app.yaml
20:22:48  + echo snapshot_es
20:22:48  + awk -F_ {print $NF}
20:22:48  + locale_name=es
20:22:48  + tools/devshell.py --host localhost:9085 --script dev/dev_appserver/run_sync.py ../snapshot_es es
20:22:48  Could not connect to localhost:9085. Is it running?
```
I have no idea why the dev-appserver isn't starting up (or maybe it is
and we just need …
=> [🔥AUDIT🔥] Log the appserver log when the devshell script fails.

build_current_sqlite.sh
We are seeing the build-sqlite job fail with the following log message
after finishing the english run and starting the spanish run:
```
RuntimeError: Port 8011 is in use, but not by pubsub-emulator like is
needed
```
This indicates to me that the pubsub emulator was not properly shut
down (like it's hanging or something).  Adding a few kill commands
should help with that.
Ran
python third_party/frankenserver/dev_apprver.py --application=khan-academy --datastore_path=../current.sqlite --port=9085 --require_indexes=yes --skip_sdk_update_check=yes --automatic_restart=no --admin_port=0 --max_module_instances=1 --log_level=info --host=127.0.0.1 ./app.yaml &
lsof -t -iTCP:8012 -o -iTCP:8081 -iTCP:8011 | xargs kill -15
and then did
ps xfww
and saw that …
=> [🔥AUDIT🔥] Explicitly kill dev-server subprocesses as well as dev-server.

build_current_sqlite.sh
In my local (ubuntu) testing, `kill -15` with no other args doesn't
give an error.  But it does on jenkins, so add the `-r`.
`xargs -r` isn't supported on os x, but I don't think that's a concern
for jenkins jobs, which are never going to run on a mac.
Will run on jenkins
=> [🔥AUDIT🔥] Use `xargs -r` to make sure we don't run it if we don't need to.

vars/notify.groovy
BUILD_URL ends with a slash, so adding a slash like I was doing
yielded urls like:
https://jenkins.khanacademy.org/job/deploy/job/deploy-internal-services/50//
Now there's just one `/` at the end.
Both urls work, at least in chrome, so this is really just cosmetic.
Issue: https://khanacademy.slack.com/archives/C8Y4Q1E0J/p1637687766119700
=> [🔥AUDIT🔥] Concat our urls so they only have one `/`, not two.

jobs/build-webapp.groovy, jobs/deploy-znd.groovy
graphql-gateway-2 (aka go-go-graphql-gateway) uses a different style
of config file than graphql-gateway (aka apollo).  We need to upload
them both.
I protect this upload in an "if exists" check so things don't suddenly
start to break when we move to only having one go gateway again.
Issue: https://khanacademy.atlassian.net/browse/INFRA-7074
groovy jobs/deploy-znd.groovy
=> Upload the go-style gateway config to gcs when we upload the js-style one.

jobs/deploy-fastly.groovy
When a fastly deploy goes wrong, it's a panic situation.  This PR
makes it easier to recover by always emitting, to the `#fastly` slack
channel, the sun command to run to undo the deploy.
Issue: https://github.com/Khan/internal-services/pull/71
https://jenkins.khanacademy.org/job/deploy/job/deploy-fastly/1699
New output at
https://khanacademy.slack.com/archives/CCCC6HZ4K/p1643056437020100
=> Notify in the fastly slack channel how to roll back on error.

build_current_sqlite.sh, jobs/build-current-sqlite.groovy
The main one is to wait longer for graphql-gateway to start up.  In my
local tests it can take over a minute.  I'm suspecting that is the
cause of these errors in the logs:
> 13:18:54  ERRO[0010] Post "http://localhost:8102/graphql/CreateUserModelsInOtherServices": dial tcp 127.0.0.1:8102: connect: connection refused
However I can't be sure because it's hard to tell what service is
outputting what logs.  I add some logic here to prepend every line of
log output with its service, to ease debugging.
I also found a typo involving redis-pid.
Issue: https://jenkins.khanacademy.org/job/misc/job/build-current-sqlite/1216/console
Fingers crossed -- will try running this again and see how it goes!
=> Make some changes to try to get "build-current-sqlite" working again.

build_current_sqlite.sh
python calls graphql-gateway-2 to update settings so it's now required.
Additionally add sync feature flags to the script.
Issue: INFRA-7279
ran it.
=> Add graphql-gateway-2 to services in build_current_sqlite

jobs/go-codecoverage.groovy
This job implements code coverage to be reported on via Jenkins + Cobertura per ADR #515.
It will checkout master and run all tests in /services and /pkg and report on their code coverage. This job is for team information purposes and is not used in conjunction with a deploy because it takes a couple hours to run and generate the report. Gaining insight into application-wide coverage should be useful to teams who want to increase their code coverage and quality.
This job has been running on jenkins for some time now. Now that I've worked out the issues, I'll commit it to this project and update the job to reference this groovy script.
Issue: None
- This job has been running on jenkins here: https://jenkins.khanacademy.org/job/misc/job/go-codecoverage/
=> Added go-codecoverage.groovy to /jobs

jobs/deploy-webapp.groovy
During the rollback in our KRD [1] we noticed that we deploy a wrong
version of the dispatch.yaml. We can visibly see the traffic goes
to the new version of the graphql-gateway.
This is due to the local version of the code would still be on the
latest version, and some operations such as updating `dispatch.yaml`
will pick up the config from local code.
This diff ensure that we use
[1] https://jenkins.khanacademy.org/job/deploy/job/deploy-webapp/9990/
Issue: https://khanacademy.slack.com/archives/C8XGW76FQ/p1646079377461529
Test plan:
1. Merge this which should deploy this to jenkins
2. Create a fake deploy that have a harmless route redirection (e.g.
redirecting a https://khan-academy.appspot.com/trace  to service-testbed)
3. Deploy, set-default and immediately force a rollback.
4. …
=> Ensure that rollback code is of the right version

weekly-maintenance.sh
The old one has been broken for months, maybe longer -- it times out.
I'm writing a new one in Go.  Let's start running it in our weekly
maintenance job; it can't do any worse than the old one!
Issue: https://khanacademy.atlassian.net/browse/INFRA-7672
I ran this new script manually.:
```
% gcloud --project khan-internal-services compute ssh ubuntu@jenkins-server
$ sudo su - jenkins
$ cd ~/jobs/misc/jobs/webapp-maintenance/workspace/webapp
$ tools/prune_graphql_safelist.sh --prod
{"data":{"entitiesAfterPruning":"1916","entitiesBeforePruning":"1916","numDeletionErrors":"0"},"message":"Finished pruning, entitiesAfterPruning = 1916, entitiesBeforePruning = 1916, numDeletionErrors = 0","severity":"INFO"}
```
So it successfully ran.
=> Use the new graphql safelist-pruning script.

build_current_sqlite.sh, jobs/build-webapp.groovy
I'd lke ot move prime-query-plan-cache from graphql-gateway-2 to
graphql-gateway.  We shouldn't need to change our jenkins jobs when we
do that!  We already have a symlink in tools/ that we can/should use
instead.
While in the area, I cleaned up a few other graphql-gateway references.
Issue: https://khanacademy.atlassian.net/browse/INFRA-7739
=> [🔥AUDIT🔥] Run prime-query-plan-cache via the shell symlink, not directly.

jobs/update-ownership-data.groovy, jobs/webapp-maintenance.groovy
update-ownership-data failed last night because master had a change to
`.gitignore` in it, which caused some previously ignored files to be
un-ignored.  We didn't clean them up (that is, delete them) because
our cleaning happens in `safeSyncToOrigin`, which runs before the
merge from master.
To fix this, I just manually clean again after merging from master.
Only two scripts do a safeMergeFromMaster, so I didn't have to clean
up that many places.  (I thought of moving the `git clean`s to
safeMergeFromMaster itself, but I thought that wasn't safe because in
theory you could call merge-from-master at any time, including when
your workspace wasn't entirely clean, and I didn't want to do
destructive activities on something that sounds like it's only a merge
command.) …
=> [🔥AUDIT🔥] Go a git clean after merging from master.

build_current_sqlite.sh
Nothing in master users graphql-gateway-2 anymore, so we don't need to
start it up in this script.  Which is good, because soon that service
will be going away entirely!
Issue: https://khanacademy.atlassian.net/browse/INFRA-7739
Fingers crossed -- we'll make sure build-current-sqlite succeeds tomorrow.
=> [🔥AUDIT🔥] Remove graphql-gateway-2 from the list of required services.

vars/onWorker.groovy, vars/withVirtualenv.groovy
My latest change to install pip3 in /usr/local/bin (for keeper) had
the unfortunate effect that it made all the jobs prefer the pip3 in
/usr/local/bin to the python2 pip that lives in the virtualenv.  This
is because we accidentally were putting /usr/local/bin very high up in
the path, above the virtualenv.
I fix this in two ways:
1) I start the virtualenv *after* other path-munging, not before.
2) When we inherit the virtualenv (so we don't need to start it)
I add the virtualenv dir to the front of PATH again, just in case.
The latter is necessary because in the "already-set-up" case
withVirtualenv leaves PATH alone, but onWorker munges PATH a second
time (so all its stuff is on PATH twice, oh well), which makes it so
the virtualenv isn't first again.  We fight …
=> [🔥AUDIT🔥] Make sure the virtualenv comes before /usr/local/bin on $PATH.

vars/onMaster.groovy
`onWorker` says what worker machine a job is running on, but
`onMaster` didn't say it was running on master.  This PR fixes that.
Issue: https://khanacademy.slack.com/archives/C8Y4Q1E0J/p1650297296717879
groovy vars/onMaster.groovy
=> When we run on jenkins-master, print that fact.

build_current_sqlite.sh
The `test_push_sub` endpoint is so noisy that the logs were filling up
the disk, causing the current.sqlite build to fail.  I hackily work
around it for now by just turning off the pubsub entry that calls that
endpoint.  We should really have a more principled solution, but this
is the most straightforward.
Issue: https://khanacademy.slack.com/archives/C02NV1DPJ/p1654708264283569
I ran the new perl command manually and got this diff:
```
diff --git a/pubsub.yaml b/pubsub.yaml
index eae0c76864b..d99305efd1e 100644
--- a/pubsub.yaml
+++ b/pubsub.yaml
@@ -65,9 +65,6 @@
- topic: analytics-events
subscriptions:
-    devOnly_push_sub_analytics:
-      endpoint: https://analytics-dot-khan-academy.appspot.com/api/internal/pubsub/subscription/test_push_sub
- …
```
=> [🔥AUDIT🔥] Suppres the test_push_sub log output when building current.sqlite.

build_current_sqlite.sh
We can't run `make serve` in build_current_sqlite.sh because, um, it
didn't work for some reason.  I think INFRA-7279 has more details.  In
any case, this means we need to list the services to start manually.
It's easy to forget to do this, and indeed we did forget when we added
fake-gcs as a service-dependency in #5869.  This change adds it there.
Note that we will have to get mkcert working no the jenkins machines
as well.  That will be a separate diff (in a separate repo).
Issue:  https://khanacademy.slack.com/archives/C01120CNCS0/p1654719166232869
Fingers crossed.
=> Add fake-gcs to the list of services started to build current.sqlite.

jobs/e2e-test-cypress.groovy, jobs/e2e-test.groovy
This PR runs the cypress job in parallel with the existing e2e-test job.
Issue: FEI-4480
Run the script with replay on both scripts
=> Integrate e2e-test-cypress job with Buildmaster

jobs/webapp-test.groovy, vars/notify.groovy
This wires up the new Github status check logic added to alertlib into the notify.groovy logic - making it so that the status check is added to the current commit SHA that we're working against. I made sure to add in calls to `sendToGithub` in the `call` method on both build start and completion, this will allow us to see the "pending" state more accurately in Github.
Issue: FEI-4621
I was able to test this by taking an existing test run:
https://jenkins.khanacademy.org/job/deploy/job/webapp-test/142238/
and then I clicked "Replay" and modified the Main Script and Notify to match what's in this PR and I was able to get working results!
https://jenkins.khanacademy.org/job/deploy/job/webapp-test/142250/
Pending:
Back to normal:
Success:
=> Add sendToGithub to Jenkins and wire up into webapp-test job.

jobs/e2e-test.groovy
There's an issue with the existing logic where we try to parallelize
Python/Selenium and Cypress/LambdaTest e2e tests. For some unknown
reason, LT is not being able to start some tests causing the entire test
suite to fail, and by using `parallel`, we're also seeing the main e2e
job having to wait until LT resolves (it's currently resolving after 1
hour of timeout).
This PR fixes that issue by running the LT/Cypress tests sequentially
only after the main e2e tests are completed.
Verify that the e2e job iss reporting times as before.
=> Run LT/Cypress e2e tests sequentially.

jobs/e2e-test-cypress.groovy
There's no good reason to only allow a single e2e-test-cypress job at a time, all the heavy lifting is done by the LambdaTest system, which is already heavily parallelized. While it doesn't really HURT us to not run the tests concurrently now that the e2e-test job doesn't wait on the result of this job, it's still creates a massive queue of jobs for no clear reason. Because of the way jenkins won't tell you deatils about queued jobs until it's running, it's especially hard to figure out when a given e2e-test-cypress job will run or what the status of it is.
Issue: None
Cross fingers. Twice.
=> Allow multiple LambdaTest runs to execute concurrently

jobs/deploy-znd.groovy, jobs/merge-branches.groovy, vars/kaGit.groovy
The regular deploy process merges 'master' into the deploy branch before deploying.  We want to do the same when deploying ZNDs.  This will avoid issues that can occur if a ZND is being deployed with out-of-date deploy scripts.
Issue: FEI-4674
Questions:
- Do we want to change GIT_REVISION to GIT_REVISIONS and allow people to deploy a ZND using multiple branches?
- visit a page like https://jenkins.khanacademy.org/job/deploy/job/deploy-znd/5254/
- click on replay on the left pane. Replace the contents of the "main script" window with your new deploy-znd.groovy code
- Replce the contents of the "kaGit" window with your new kaGit.groovy code
- click "run" and see how the job does
```
...
17:02:51  'kevinb-fixes' resolves to bd2f7ca76da4b854c98f24bb340072c73be64a61
[Pipeline] sh
17:02:51  + …
```
=> FEI-4674: Merge in 'master' when deploying ZNDs

jobs/e2e-test-cypress-backup.groovy, jobs/e2e-test-cypress.groovy, jobs/e2e-test.groovy
Use cypress directly (no parallelization enabled) if LambdaTest is down
Issue:FEI-4484
run with replay
=> Configure backup in case provider is down.

jobs/deploy-znd.groovy
As discovered during our ZND testing, if a ZND contains uppercase,
we will fail to lookup the static version in Fastly (see slack thread in issue).
Also from
https://github.com/Khan/jenkins-jobs/commit/d2dc0da5d3418682e222e3b9e2238d058bbb5864
it looks like previously we expect lowercase also.  So let's make the
version name lowercase.
Issue: https://khanacademy.slack.com/archives/C02NMB1R5/p1658776260277369
- Create a new ZND job using uppercase ZND name https://jenkins.khanacademy.org/job/deploy/job/deploy-znd/5292/
- Select replay from above job and copy and paste the modified deploy-znd.groovy, and Run the job https://jenkins.khanacademy.org/job/deploy/job/deploy-znd/5293/.
- Confirm the new version https://prod-znd-220725-boris-up.khanacademy.org/_api/version is indeed working.
(note …
=> Enforce ZND to use lowercase version name.

jobs/e2e-test-cypress-backup.groovy, jobs/e2e-test-cypress.groovy
Now that engineers have started to work on creating and/or porting e2e tests in
Cypress, we can safely use `master` as the default branch for running tests with
LambdaTest.
Verify that the builds run more consistently and that the `321-happy-path.spec.js` tests go back to normal.
=> [🔥AUDIT🔥] Cypress: Switch to master as default branch

jobs/e2e-test-cypress.groovy, jobs/e2e-test.groovy
We are trying to deploy a fix for a flaky test but LT still thinks that is an error
This is happening because we are using master to run the tests, so we are testing the “old” version of that test,
instead of the commit that includes the changes.
Issue: FEI-4724
run replay
=> e2e-test-cypress Jenkins job is not running against current commit hash

jobs/webapp-test.groovy
The ka-lint cache is really useful for avoiding unnecessary lints in
dev.  In theory we could save the same work at deploy-time (and other
times) on jenkins.  But we want to be extra sure everything is ok,
when we run on Jenkins, so I want to suppress the cache there.
The easiest way to do that is to just delete the cache at the
beginning of every test-run, which is what I do in this PR.
Issue: https://khanacademy.slack.com/archives/C02NMB1R5/p1661765927139029
=> [🔥AUDIT🔥] Clear out the ka-lint cache when running tests on jenkins.

jobs/webapp-test.groovy
`GIT_REVISION` could be a symbolic name, like `master` or `csilvers`.
We convert it to a sha once at the beginning of webapp-test, and use
the sha everywhere in the script, to protect against changes in the
branch between the time the script starts and when it ends.  But we
missed one place that was still using GIT_REVISION.  Now it's fixed
too.
Issue: https://jenkins.khanacademy.org/job/deploy/job/webapp-test/150581/consoleText
I ran a job successfully with these changes:
https://jenkins.khanacademy.org/job/deploy/job/webapp-test/150583/console
=> [🔥AUDIT🔥] Always refer to the current revision by sha, not name.

vars/onMaster.groovy
For some resaon, with the Jenkins upgrade Jenkins no longer reads
`.profile` on the main (jenkins-server) machine, matching the behavior
it's had on the workers for a while.  We worked around that in
`onWorker`.  Now we apply the same workaround in `onMaster`.  This
matches a TODO (though doesn't resolve it, since our workaround is
still a hack).
Issue: https://jenkins.khanacademy.org/job/misc/job/update-ownership-data/1213/
I went to
https://jenkins.khanacademy.org/job/misc/job/update-ownership-data/1213/
and clicked on `replay` and replaced the contents of onMaster.groovy
with the new version in this PR, and ran it with success.
=> [🔥AUDIT🔥] Set up path on master like we do on the workers.

jobs/e2e-test-cypress.groovy
Second change to align on how we tag LambdaTest builds.
The idea is to include tags to builds so we can start filtering builds
by env and platform, so we can start collecting better metrics around
possible flaky tests depending on the tag.
These will be the tags we'll be using from now on:
By environment: `prod` | `preprod` | `znd`.
By CI platform: `github` | `jenkins`.
This PR is responsible for doing the Jenkins-related changes to support
these tags.
In the `jenkins-job` context, we will be supporting the following
combinations:
- `preprod,jenkins` (e.g. first smoke tests or http://prod-someid-somehash.khanacademy.org)
- `prod,jenkins` (e.g. second smoke tests or http://khanacademy.org)
Issue: FEI-4766
Used the Jenkins replay feature to test changes to this job.
- First replay runs …
=> FEI-4766.2: Tag LambdaTest builds per environment / CI platform

jobs/e2e-test-cypress.groovy
Incrementing the Cypress retries from 1 to 3 to help us decreasing build
failures from LambdaTest.
Issue: "none"
Verify that LambdaTest builds are starting to get more positive results when
being triggered from deploys.
=> Increment Cypress retries in Jenkins

jobs/e2e-test.groovy
Incrementing the number of Cypress retries in the `e2e-test` jenkins job to 3.
We previously set it directly in the e2e-test-cypress job, but I noticed that
this was being override in the main test job.
N/A
=> [🔥AUDIT🔥] Increment Cypress retries in main e2e-test job

jobs/webapp-test.groovy
We had an issue where there was a deploy that deleted one python file,
which made a second python file unused (since the deleted python file
was the only client).  But we didn't catch the problem because jenkins
doesn't call all_tests_for.py on deleted files.  On the face of it
that's reasonable: what tests could you possibly have on code that
doesn't exist?!  But there are some consistency tests that care, such
as unused_file_test.py.
This PR tells jenkins to look for that case, using a new
`--deleted-mode` flag on all_tests_for.py.
Depends on https://github.com/Khan/webapp/pull/8816.
Issue: https://khanacademy.slack.com/archives/C02NMB1R5/p1663856692389019
Will run a webapp-test job using this new arg once https://github.com/Khan/webapp/pull/8816 is landed.
=> Figure out what tests need to be run for deleted files, too.

jobs/build-current-sqlite.groovy
We are going to be turning off the FMS in python, and getting rid of a
lot of the routes that dev/dev_appserver/create_user_interactions.py
is calling.  While this is all in flux, let's just keep current.sqlite
fixed in place.  We can restart it again once all the relevant
functionality is moved to Go + graphql (+ gcs).
Note that I'll have to turn off the cron via the jenkins UI as well.
But I turn it off here too so the UI changes will "stick".
Issue: https://khanacademy.atlassian.net/browse/INFRA-8358
None
=> Disable building current.sqlite every night, for now.

vars/withSecrets.groovy
This commit makes several changes to the decryption of webapp's secrets.py:
- Changes the password filename to the one in the latest aws-config scripts
- Changes the name of the encrypted file to the current one in the webapp repo
- Changes the openssl parameters to work with the current encrypted file in the webapp repo
Issue: https://khanacademy.atlassian.net/browse/TP-7594
=> Update decryption of webapp's secrets.py

jobs/e2e-test.groovy
We are currently running Python/Selenium (Py/Sel) and Cypress/LambdaTest (Cy/LT) tests in
parallel. This happens everytime the `e2e-test` job is triggered.
While debugging some Cypress/LambdaTest test builds I noticed that the Cy/LT
tests are also triggered when we retry the Py/Sel tests in Slack (via
`buildmaster`).
This change attempts to run only Py/Sel tests when a set of Python e2e tests
fail, and prevent running Cy/LT builds that are not related to this retry.
Issue: FEI-4867
In deployments, verify that the next time someone retries e2e tests, these don't
retry a LambdaTest build (or spin up a new `e2e-test-cypress` job).
=> FEI-4867: Only run Python/Selenium tests when the tests are retried

jobs/e2e-test-cypress.groovy
While taking a look at the e2e-test-cypress job, I noticed that we are not
assigning a more meaninful name to the job.
This change intends to replicate what we do in `e2e-test` so both jobs
(Python/Selenium and Cypresss) have a similar name, so that makes it easy to
identify related builds.
- Navigated to the `e2e-test-cypress` Jenkins job page.  
- Clicked on the last job that succeeded.  
- On the sidebar, clicked on the `Replay` button, and added the changes
introduced in this PR.  
- Verified that the build name changed to something more descriptive.
https://jenkins.khanacademy.org/job/deploy/job/e2e-test-cypress/5691/
=> Update e2e-test-cypress build name

weekly-maintenance.sh
This PR removes the weekly maintenance function that turns old webapp branches
into tags (old branches are branches that haven't been updated in more than 6
months). We started doing this because `git branch --contains`, which is used
by phabricator, is really slow when there are a lot of branches. The downside
of turning branches into tags is that the branch names become unusable; tags
can be deleted locally, but they're recreated by various automated processes
that push to webapp. Conflicting tag and branch names result in the error
`warning: refname '<branch-name>' is ambiguous`. We no longer use phabricator,
so old branches are no longer a problem (we think).
Issue: https://khanacademy.slack.com/archives/C013ANU53LK/p1671746937855749
Before the change I ran:
``` …
```
=> Stop turning old webapp branches into tags

jobs/e2e-test-cypress.groovy, jobs/e2e-test.groovy
Ported the logic that we use in the default e2e-test job to notify
failures to Slack using the current Python/Selenium framework.
In the Cypress case, we created a script in `webapp`
(`notify-e2e-results.js`) to be able to replicate the way we send Slack
messages about the e2e test results (for both SUCCESS and FAILURE).
This new script also uses a different Slack wrapper for NodeJS that was
created in the `webapp` repo.
**NOTE:** For more info about the logic created for the JS/Cypress
version of this script, you can take a look at this PR:
https://github.com/Khan/webapp/pull/10867
Issue: FEI-4883
1. Navigated to https://jenkins.khanacademy.org/job/deploy/job/e2e-test-cypress/.
2. Clicked on any of the last runs (e.g https://jenkins.khanacademy.org/job/deploy/job/e2e-test-cypress/6343/). …
=> FEI-4883: Notify Cypress e2ed test failures to Slack

jobs/e2e-test-cypress.groovy, jobs/e2e-test.groovy
Making some slight changes to make it look closer to the existing python
e2e job.
- Removed the option to notify if the `e2e-test-cypress` job is aborted.
- Simplified the Slack message on this repo if the job returns a failure
or is unstable.
- Included the workers logic used in the regular `e2e-test` job to make
sure this job has the right priority.
Issue: FEI-4883
1. Navigated to https://jenkins.khanacademy.org/job/deploy/job/e2e-test-cypress/.
2. Clicked on any of the last runs (e.g https://jenkins.khanacademy.org/job/deploy/job/e2e-test-cypress/6343/).
3. Clicked on the `Replay` link.
4. In the `Main Script` textarea, I replaced the contents of that with
the contents of the `e2e-test-cypress.groovy` file in this PR.
5. Clicked on the `Run` button.
6. Verified that the new job …
=> FEI-4883.2: E2E Cypress - Tidy up jenkins job

jobs/e2e-test-cypress.groovy, jobs/e2e-test.groovy
Re-introduces the changes added in #78, but fixes an issue that was
introduced in the `e2e-test.groovy` file.
The issue was that I didn't properly pass the value of
`USE_FIRSTINQUEUE_WORKERS` as a `boolean`, and instead this was being
passed as a `string`.
This caused the smoke tests job to fail, as the `e2e-test.groovy` file threw
the following error:
https://jenkins.khanacademy.org/job/deploy/job/e2e-test/44947/execution/node/71/
```
java.lang.ClassCastException: hudson.model.StringParameterValue.value expects class java.lang.String but received class java.lang.Boolean
at org.jenkinsci.plugins.structs.describable.DescribableModel.coerce(DescribableModel.java:492)
at org.jenkinsci.plugins.structs.describable.DescribableModel.buildArguments(DescribableModel.java:409)
at …
```
=> [fix] FEI-4883.2: E2E Cypress - Tidy up and fix issues

jobs/build-webapp.groovy
Historically, when there have been changes to index.yaml, queue.yaml,
or pubsub.yaml, that's prompted a deploy of the default module (even
if the python code itself hasn't changed!), and deploy_to_gae.py would
update those yaml files in addition to updating the default module.
Now that python is going away, we want to separate those
responsibilities.  The plan is to create three new pseudo-services,
index.yaml, queue.yaml, and pubsub.yaml.  And should_deploy.py can say
we need to deploy to those services.  Jenkins notices this and uploads
the relevant yaml file to GAE.
This is the jenkins part of things: it notices when the new
pseudo-services are being deployed and uploads the yaml files.  Once
this is tested, I will change should_deploy.py to emit these
pseudo-services when appropriate, …
=> Allow jenkins to update index/queue/pubsub.yaml outside deploy_to_gae.py.

jobs/build-webapp.groovy
I claimed we update queue.yaml in build-webapp and not deploy-webapp,
but that's not really true: we do it in both places.  In the first we
add things, in the second we delete.  This updates the comments to be
clearer.
Issue: none
none
=> [🔥AUDIT🔥] Fix the comments to be more accurate.

jobs/build-publish-image.groovy
I thought I had put in symlinks from the old location to the new
during this transition period, but I guess not.  We'll just update.
Issue: https://khanacademy.slack.com/archives/C49296Q7P/p1675116384824979
Test plan:
Will try deploying a new publish image
=> [🔥AUDIT🔥] Point to the new location for some publish scripts.

jobs/e2e-test-cypress.groovy, jobs/e2e-test.groovy, jobs/firstinqueue-priming.groovy, jobs/webapp-test.groovy, vars/onWorker.groovy
We are currently priming 20 workers that are used by the Python/Selenium
e2e tests. We noticed that the Cypress e2e tests are taking ~2 minutes
before a worker becomes available so the job starts running and this is
due to the Python e2e tests taking up all the available workers.
This PR adds one default worker that will be used by the Cypress e2e
tests so that both `e2e-test` and `e2e-test-cypress` jobs can start
around the same time.
Note that Python and Cypress e2e tests are run in parallel, so we need
to prime+run then at the same time.
I've tested all the Jenkins jobs that are affected by this change using
the Replay feature. I checked that these changes didn't introduce any
regression:
1. Ran the `firstinqueue-priming` job first to prime the machines: …
=> Add one default worker for priming Cypress e2e tests

jobs/build-webapp.groovy, jobs/deploy-znd.groovy
In order for Cloud Run services to handle traffic for versions that don't exist in Cloud Run we need to create traffic tags. These traffic tags is how we can send traffic to default revisions.  We need to do this when we build webapp and when we deploy znds.
Issue: https://khanacademy.atlassian.net/browse/INFRA-8963
Im going to kick off a znd build for service-testbed and check the logs.
=> Added work for creating cloud run tasks in jenkins

jobs/e2e-test-cypress.groovy
We made some changes in https://github.com/Khan/webapp/pull/11664 to be able to
identify if the LambdaTest platform is going to hit queue timeout errors.
This happens when there are multiple builds in parallel, causing our e2e tests
to fail b/c there are no more available machines to run the tests.
This check was introduced in the `webapp` repo, and the only thing that we need
to do in Jenkins to support it is to include the Slack token so we can send a
notification to the FEI team in case we hit this queue timeout error.
Issue: FEI-4923
Using replay, I verified that these changes worked fine:
https://jenkins.khanacademy.org/job/deploy/job/e2e-test-cypress/7050/console
=> FEI-4923.2: Include Slack token in the lambdatest step

jobs/clean-queues.groovy, jobs/update-ownership-data.groovy
We had a problem where the `clean_queues` job deleted a taskqueue it
shouldn't have, and it took us a while to track down because nobody
left at the company even realized this job existed!
This PR tries to help with that a little by having most cron-based
jenkins jobs send to slack on success, rather than just on failure.
That way at least people will have a chance of knowing the job exists.
The only cron-jobs that I did not modify are `make-allcheck` and
`find-failing-taskqueue-tasks`, since they send to slack on success in
any case (as part of their job output); and `update-i18n-lite-videos`,
which pings `@cp-support` when it talks to slack, which we don't
want to do on success (it creates a ticket!)
Issue: https://khanacademy.atlassian.net/browse/INFRA-9008
=> Change most of our cron-based jenkins jobs to send to slack on success.

jobs/build-webapp.groovy, jobs/deploy-znd.groovy
I just use the same logic as in build-webapp.groovy.
While in the area I got rid of the dispatch_yaml support in
build-webapp.groovy, now that dispatch.yaml is gone.
Issue: https://khanacademy.slack.com/archives/C01120CNCS0/p1677288416167349?thread_ts=1677287993.252749&cid=C01120CNCS0
groovy jobs/deploy-znd.groovy.
=> Allow znd's to deploy index.yaml, pubsub.yaml, etc.

jobs/clean-queues.groovy
We will no longer run it.  Amos already disabled this job via the UI,
but this change will make sure it doesn't come back again (until we
want it to).
The issue is the job deleted some queues that were still in use.  We
are being very careful with the code before turning this back on again
(if we ever do).
Issue: https://khanacademy.atlassian.net/browse/INFRA-9008
None
=> [🔥AUDIT🔥] Disable the clean-queues.groovy cronjob.

jobs/build-publish-image.groovy, jobs/update-translation-pipeline.groovy
We keep running out of disk space on build workers, which then requires deleting
them. Instead, if we first prune images we can avoid this issue when building the
publish-worker and translatios-pipeline. Even if it takes a bit longer, since
they're not frequently built.
However, since `build-worker` is shared with `deploy-webapp`, `deploy-znd`, etc.
We need to ensure prunning Docker images is not going to slow down build other jobs!
Issue: https://khanacademy.slack.com/archives/C49296Q7P/p1679938601807059?thread_ts=1679706002.920919&cid=C49296Q7P
Test Plan:
- Verify deploying webapp and ZND is not affected
- Verify building images works for:
https://jenkins.khanacademy.org/job/deploy/job/update-translation-pipeline/build?delay=0sec …
=> Prune docker images before building publish-worker and translations-pipeline

jobs/webapp-test.groovy
This adds a new test client, `typecheck_test_client.sh` that basically will replace `flow_test_client.sh` once flow is replaced with TypeScript (TS) fully.
Issue: FEI-4961
Land this and then rerun the job for https://github.com/Khan/webapp/pull/13083 to see that it works.
=> Add typecheck_test_client.sh to support TS

jobs/build-publish-image.groovy, jobs/update-translation-pipeline.groovy
We're currently running into an error when attempting to build a publish worker image:
```
WorkflowScript: 45: illegal string body character after dollar sign;
solution: either escape a literal dollar sign "\$5" or bracket the value expression "${5}" @ line 45, column 6.
sh("[ $(df -BM --output=avail . | tr -cd 0-9) -gt 1500 ] || docker image prune -af")
```
🤞 that switching to single quotes solves the problem.
Full error: https://jenkins.khanacademy.org/job/deploy/job/build-publish-image/219/console
Issue: none
Re-run the publish worker job.
=> Fix publish worker and TAP jobs

jobs/update-ownership-data.groovy, jobs/webapp-test.groovy
We now have runpytests.sh as a wrapper around runtests.py to properly
handle both python2 and python3.  Let's use it!
Issue: https://khanacademy.atlassian.net/browse/INFRA-9106
groovy jobs/update-ownership-data.groovy
groovy jobs/webapp-test.groovy
=> Use runpytests.sh in our jenkins jobs.

weekly-maintenance.sh
It would be very problematic if we accidentally deleted the graphql
safelist datastore models!  Nobody could do anything.  Let's back them
up every week so we can do a manual restore.  (Maybe one day in the
future we'll write a script to do an automated restore.)
Issue: https://khanacademy.atlassian.net/browse/INFRA-6521
I ran the new command manually on jenkins-server, wich success.
=> Backup our graphql safelist as part of our weekly backup.

jobs/build-webapp.groovy
We moved this rule fraom graphql-gateway/ to queryplanner/ some time
ago.  We tried to run in both directories for builds of commites
before that migration.  But the migration was like over a year ago
now!  I don't think we need to support the old location anymore.
Issue: https://jenkins.khanacademy.org/job/deploy/job/build-webapp/39021/execution/node/198/log/
=> [🔥AUDIT🔥] Only run `deploy-gateway-config` in the queryplanner directory now.

jobs/deploy-znd.groovy
We recently changed this for deploying webapp and need to change it for ZNDs too.
Issue: NA
Test Plan:
Fingers crossed, we can always revert if we need to
=> ZNDs:skip deploy-gateway-config on graphql-gateway

jobs/delete-version.groovy
We run delete-versions continuously -- probably because we have so
many versions at the moment, we could really do a better job of
managing that -- and it's not enough to debug.  Let's keep a lot more
logs so we can debug better.  The logs are short so it should be ok.
Issue: https://khanacademy.slack.com/archives/C01120CNCS0/p1683676021846129
None
=> [🔥AUDIT🔥] Keep a metric ton of delete-versions logs.

jobs/webapp-test.groovy
We now have a mypy pseudo-language when running webapp tests.  We need
to tell the webapp-test job to run them.
Issue: https://khanacademy.atlassian.net/browse/INFRA-9198
=> Run mypy tests.

jobs/webapp-test.groovy
Now that py_test_client.sh is in master, we can call it directly,
rather than having to go through the shim.
Issue: none
=> [🔥AUDIT🔥] Use the proper test-runner for python tests now.

jobs/webapp-test.groovy
I got rid of flow_test_client.sh in https://github.com/Khan/webapp/pull/15380 since we're no longer using Flow anywhere.
Issue: None
- land and deploy ts-static which migrates the static service to TypeScript
=> [🔥AUDIT🔥] Remove command to run flow_test_client.sh

jobs/webapp-test.groovy
We weren't able to deploy the TypeScript migration so we'll need to contuine reporting Flow errors in the meantime.  See #118 for the original change.
Issue: None
- n/a
=> [🔥AUDIT🔥] Revert #118

jobs/webapp-test.groovy
Go does not support flags like `-j1`.  It needs to be `-j 1`.
Issue: https://khanacademy.slack.com/archives/C02NMB1R5/p1690449539319869
Fingers crossed, will try running make-allcheck again
=> [🔥AUDIT🔥] Fix the flags passed to runtests.sh.

jobs/e2e-test.groovy
We're moving from keeper to google secrets manager.  We've already
transitioned over all the secrets, and given jenkins access to all the
ones it needs.  This changes the script to make use of that.
`git grep keeper` shows no other jobs need to be changed.
I also ran:
```
gcloud --project khan-academy secrets get-iam-policy lambdatest_admin_account
```
and ensured that group:secrets-prod-ro@khanacademy.org has the
secretAccessor role, so Jenkins can read this secret.
Issue: INFRA-XXXX
=> Change the e2e job to get its secrets from gsm instead of keeper.

weekly-maintenance.sh
To support a gradual rollout, in #114 I made it so we only clean the
lol ka-content bucket.  That seems to have been going well, so now I
extend it to all bucket!
Issue: https://khanacademy.slack.com/archives/C49296Q7P/p1686584563057689
See above
=> Clean up all old ka-content buckets.

jobs/update-devserver-static-images.groovy
When called (which we expect to be every day), this job rebuilds
all the images that we use for local dev-server -- one for each
first-party service in webapp -- and uploads them to the google
container registry.  It then updates a file in webapp saying what
git commit corresponds to the latest-pushed images, and checks
that into the `automated-commits` branch.
Issue: https://khanacademy.atlassian.net/browse/INFRA-9151
`groovy jobs/update-devserver-static-images.groovy` gave only
the expected two errors around `@Library`.
Will try running it and see what happens!
=> Add a job to update the dev-server static images in gcloud.

jobs/update-devserver-static-images.groovy
One silly mistake, and one not so silly -- I guess the PATH for
jenkins jobs is not what I expected.
Issue: https://jenkins.khanacademy.org/job/misc/job/update-devserver-static-images/4/console
https://jenkins.khanacademy.org/job/misc/job/update-devserver-static-images/5/console
=> [🔥AUDIT🔥] Fix the update-devserver-static-images script after running it in real life.

jobs/update-ownership-data.groovy
runpytests doesn't exist anymore.  We can just use the main runtests
runner.
Issue: https://khanacademy.slack.com/archives/C3UDL9QN7/p1694167714011689
Fingers crossed, will run this job manually
=> [🔥AUDIT🔥] Replace runpytests.sh with runtests.sh.

jobs/e2e-test.groovy, vars/notify.groovy
We renamed the slack channel in
https://khanacademy.slack.com/archives/C0BBDFJ7M/p1693351774709549 but
never changed the code to match.
Issue: https://khanacademy.slack.com/archives/C01120CNCS0/p1694187012362329
=> [🔥AUDIT🔥] Rename #dev-support-log to #deploy-support-log.

jobs/webapp-test.groovy
The latter is gone now, replaced by the former.  The test-size flag
has also gone away (we don't have any "huge" tests left anymore, so
it's become a non-issue).
Issue: https://khanacademy.slack.com/archives/C02NMB1R5/p1694542433441139
groovy jobs/webapp-test.groovy
=> [🔥AUDIT🔥] Tell people to run runtests.sh, not runpytests.py.

jobs/update-devserver-static-images.groovy
The upload-all-static-images rule can modify some other generated
files, that we don't care about.  We reset everything in the client
except for the one file we explicitly care about.
Issue: https://khanacademy.slack.com/archives/C3UDL9QN7/p1694558657116679
=> [🔥AUDIT🔥] Ignore updated generated files when creasting devserver images.

jobs/update-devserver-static-images.groovy, vars/onMaster.groovy, vars/onWorker.groovy
Sadly, jenkins doesn't exec `.profile` or `.bashrc` when running
jenkins jobs, it just uses the same path the jenkins binary uses.
On the workers, the jenkins binary (actually the `jar slave.jar`
process) runs via ssh, which *does* exec `.profile`, so all jenkins
jobs on workers run with the path that's in `.profile`.
But on the main jenkins server, the jenkins binary (`jar jenkins.jar`)
runs via systemd, which uses its own default path.  In particular,
systemd runs as root (and later does a proces-chown to the jenkins
user), so it does not use jenkins's .profile.
There might be some way to change this in systemd, but that's pretty
black magic.  Instead, we just set the path we want in our
onWorker.groovy and onMaster.groovy scripts, which run at the
"outside" of all our jenkins jobs. …
=> Make the paths set in onWorker and onMaster match .profile.

jobs/build-webapp.groovy
While preparing the post mortem for #incident-20230911 I noticed that messages originating from our Jenkins jobs don't format the services list as nice as Sun III does. 
Here's how Sun formats them:
And Mr. Monkey before this PR:
| [Mr. Monkey Deploy Failure](https://khanacademy.slack.com/archives/C096UP7D0/p1694558999515299?thread_ts=1694557986.518789&cid=C096UP7D0) | [Mr. Monkey Just Uploaded](https://khanacademy.slack.com/archives/C096UP7D0/p1694559610890579?thread_ts=1694557986.518789&cid=C096UP7D0)  |
| ------------------------- | ------------------------- |
| <img width="382" alt="image" src="https://github.com/Khan/jenkins-jobs/assets/77138/88411f38-8ad2-4c37-9449-b39b81da7c9d"> | <img width="391" alt="image" src="https://github.com/Khan/jenkins-jobs/assets/77138/57e86ffc-8415-4284- …
=> Format services lists

jobs/webapp-test.groovy
We don't use Flow for any of our code in webapp anymore.  This is evidenced by the fact that there are no longer any .flowconfig files in that repo.
NOTE: This should be merged before deploying https://github.com/Khan/webapp/pull/16759.
Issue: FEI-5292
- n/a
=> FEI-5292: Don't run flow_test_client.sh

jobs/build-webapp.groovy, jobs/delete-version.groovy, jobs/deploy-webapp.groovy, jobs/e2e-test.groovy, jobs/webapp-test.groovy
We reap old logs periodically so the jenkins-server disk doesn't fill
up.  But we've been finding sometimes we wish some logs stayed around
a bit longer, for debugging.  This PR makes us save more, to help with
that.
Our jenkins-server has a huge amount of disk space free at the moment
-- something like half a petabyte -- so I'm not worried about logs
filling it up.
Issue: https://khanacademy.slack.com/archives/D9SJ6VASC/p1695073769786779
groovy jobs/*.groovy
=> Keep around more of our deploy logs, for longer.

jobs/build-webapp.groovy, jobs/deploy-webapp_slackmsgs.groovy
Some Jenkins jobs still have slack messages referring to @dev-support (S41PPSJ21) instead of @deploy-support (S05M3QU7WJE)
shrug?
=> Update references to deploy-support Slack team (from dev-support)

vars/buildmaster.groovy
We are having issues aborting jobs and I have traced it back to a race condition between the http request we send to buildmaster for `prompt-status` for `set-default` and when the message for aborting a job is processed by jenkins.  Its unclear to me what error it is we are getting when the request fails so I am adding logging for it.
Issue: https://khanacademy.atlassian.net/browse/INFRA-9495
groovy vars/*.groovy
=> [🔥AUDIT🔥] Logging for failed http requests to buildmaster

jobs/webapp-test.groovy, vars/notify.groovy
This makes it consistent with all the other types.  Since we want to
always send to github, the `when` is all possible states.  (Though
maybe we don't want it for aborted?)
Issue: https://khanacademy.slack.com/archives/C013ANU53LK/p1697576502336959
Will test on jenkins
=> Add a `when` to the github notification type.

jobs/update-i18n-lite-videos.groovy, jobs/webapp-maintenance.groovy, vars/notify.groovy
Looking over the alertlib code, I noticed that the secrets that
alertlib needs to send email -- sendgrid_username and
sendgrid_password -- do not exist in secrets.py, and possibly haven't
for a long time.  This means that sending to email would never work.
Given that, in jenkins, we only use send-to-email mode for two jobs
and then only on failure, and given that those jobs haven't failed in
months and months, it's possible that this feature hasn't worked for a
long time and we never noticed.  (Especially since the email goes to
jenkins-admin, which as far as I know I'm the only one who ever looks
at it.)
So let's just get rid of this feature, and depend to sending to slack
on failure.  That seems to have been working well so far.
I considered trying to fix send-to-email instead, by …
=> Get rid of send-to-email support, which hasn't worked in a long time.

jobs/make-allcheck.groovy, vars/notify.groovy
It was only being used in one place, and as far as I can tell that one
place never worked.  Which is good: the allcheck job hasn't passed
in a year and a half, and we don't need a jira task created for that
fact every night.  The existing slack notifications are more than
sufficient.
So let's get rid of it, not just for cleanliness but
so I can clean up the secrets-requirements of jenkins a little bit.
Issue: none
=> Get rid of the send-to-bugtracker option in jenkins notify().

jobs/build-webapp.groovy, jobs/deploy-fastly.groovy, jobs/deploy-webapp.groovy, jobs/deploy-znd.groovy, jobs/e2e-test.groovy, jobs/emergency-rollback.groovy, jobs/find-failing-taskqueue-tasks.groovy, jobs/firstinqueue-priming.groovy, jobs/notify-znd-owners.groovy, jobs/qa-metrics.groovy, jobs/update-i18n-lite-videos.groovy, jobs/webapp-test.groovy, vars/buildmaster.groovy, vars/kaGit.groovy, vars/notify.groovy, vars/withSecrets.groovy, vars/withSecrets.txt
We're working to get rid of secrets.py (at least once the SAT product
goes away, and we no longer have any python2 in prod).  One large
remaining client is jenkins, which uses `withSecrets()` in a lot of
places.  This PR works to normalize those uses.
It does this in 2 ways:
1. Some uses are unnecessary: they either call python code that
doesn't require secrets, or they don't even call python code at all
anymore.  I just removed those withSecerts calls.
2. Some uses are just for slack: they either call a python script that
only uses secrets to talk to slack, or they call alertlib directly,
to talk to slack.  In those cases, I use a new
withSecrets.forSlackAlertlib only.  Right now that is just an alias
for `withSecrets`, but in a follow-up PR I'll make it fetch just
the one secret (and …
=> Reduce how much we depend on secrets.py in jenkins-jobs.

jobs/make-allcheck.groovy, vars/notify.groovy, vars/withSecrets.groovy
Now, when you send to slack or github using alertlib, we only load the
one slack secret (or github secret) needed for this.  And we load it
directly from GSM, rather than depending on secrets.py.
As a happy side-effect, this means we can now use use alertlib without
needing webapp cloned.  I take advantage of that by no longer cloning
webapp in the make-allcheck job, which we used to do just to get
secrets for sending alerts to slack.
Issue: none
Will try running on jenkins!
=> Provide the ability to only load only a few secrets for calling alertlib.

jobs/build-webapp.groovy
I rewrote the deploy script to get the secret directly from gsm, so it
doesn't need secrets.py.
Issue: None
Will do a test deploy on jenkins
=> [🔥AUDIT🔥] Don't decrypt secrets for uploading the graphql-safelist.

jobs/deploy-fastly.groovy
In fastly, we send to slack at deploy time, not just set-default time.
I don't know how I missed that before.
Issue: none
Will try a fastly deploy
=> [🔥AUDIT🔥] Add secrets in another place we send to slack.

jobs/deploy-webapp.groovy, vars/withSecrets.groovy
There are a couple of scripts we run that send data to stackdriver:
monitoring and set-default.  Let's make sure they have the secrets
they need.
While writing this I discovered a bug in how we were accounting for
how the secrests blocks were being used, meaning that we weren't
deleting secrets-files when we were done with them, like we were
supposed to.  I fixed that up too.
Issue: None
Will try a deploy
=> [🔥AUDIT🔥] Decrypt both slack and stackdriver secrets, in two places.

vars/withSecrets.groovy
We were having an issue where multiple jobs running in parallel all
tried to create a secrets.py file at the same time.  Since we create
them incrementally, they were stepping on each other, causing
problems.
I solve that not by locking, but by letting each job create its own
secrets.py file, and then using an atomic `mv` file to create the
final secrets.py.  So it should always have a valid value.
Issue: none
Will try a deploy
=> [🔥AUDIT🔥] Create our secrets.py files atomically.

vars/withSecrets.groovy
We were doing:
```
rm foo
mv foo.tmp foo
chmod 600 foo
```
which is a race condition because if two jobs are doing that
simultaneously, one can do the `chmod` while the other is between the
`rm` and the `mv`, and then the chmod fails.
I get rid of the `rm`, which wasn't necessary, to avoid this.
Issue: https://jenkins.khanacademy.org/job/deploy/job/deploy-webapp/16349/flowGraphTable/
Will try deploying
=> [🔥AUDIT🔥] Make our rename of secrets.py more atomic.

weekly-maintenance.sh
This cleaned up translations directories that don't even exist anymore.
Issue: https://jenkins.khanacademy.org/job/misc/job/webapp-maintenance/267/execution/node/103/log/
I ssh'ed to jenkins-server and ran:
```
$ ls jobs/*/jobs/*/workspace*/webapp/genfiles/translations
ls: cannot access 'jobs/*/jobs/*/workspace*/webapp/genfiles/translations': No such file or directory
```
=> Get rid of the obsolete 'clean_genfiles' weekly cleanup.

jobs/deploy-webapp.groovy
We are having random deploy jobs getting stuck causing all sorts of nasty issues in the deploy queue with seeming stuck jobs after a user has abort their deployment. The theory is that abort signals from jenkins to threads are not working because the threads are in uninterruptible cycles.  To help us determine this I have added slack alerts to the `#infrastructure-deploys` channel to let us know that we pontentially have deploy-webapp jobs that are stuck.
I have added logic to trigger an abort but I have it disabled to start with to ensure that we have the correct logic in place before potentially start to abort jobs that shouldn't be.  Once this is out and we can test it, we can enable the logic to abort build that we deem "stuck".
Issue: …
=> Added logic to detect and alert of potentially stuck deployment jobs

vars/notify.groovy
We have a theory that the call to gcloud is throwing an exception in notify.log when jenkins is aborting a job, but the exception message is null. And there is no clear way to know what exception was thrown. So I am including the class name for the exception being thrown hoping to help us verify the theory.
Issue: https://khanacademy.atlassian.net/browse/INFRA-9495
This one is hard to reproduce, so hoping we can see the message when a job is stuck which we are reporting in `#infrastructure-deploys`
=> [🔥AUDIT🔥] Print class name for exceptions in notify.log

vars/buildmaster.groovy
This is part of our continuing effort to get rid of -- or at least
minimize -- secrets at rest on the Jenkins machine.  Once this is
landed, we can get rid of all the foo.secrets files in `~jenkins/` on
jenkins-master!
Issue: none
Will try to run a deploy
=> Access the buildmaster token from GSM, not from a file on disk.

jobs/deploy-webapp.groovy, jobs/webapp-test.groovy, vars/buildmaster.groovy, vars/kaGit.groovy, vars/notify.groovy, vars/retry.groovy
If a jenkins job is aborted, every process gets passed an
AbortException.  But it's possible to swallow that exception if your
code is in a try/catch.
This PR looks at every `catch` in our codebase, and if the `catch`
doesn't always rethrow anyway, I add a call to a function that checks
if the job has been aborted, and if so rethrows the exception (which
is presumably AbortException).
That should resolve issues like
https://jenkins.khanacademy.org/job/deploy/job/deploy-webapp/16256
where a job got aborted but stuff kept on running anyway, because the
`notify.log()` function swallowed the abort exception.
Issue: https://khanacademy.atlassian.net/browse/INFRA-9495
Am mostly just concerned this doesn't break anything; we'll have to
land it and see.
=> Make sure we check for abort every time we catch an exception.

jobs/e2e-test.groovy
The deploy-username is set when the e2e tests are run by jenkins, but
not when run by hand.  Let's make sure the script gracefully handles
that case.
Issue: https://jenkins.khanacademy.org/job/deploy/job/e2e-test/53606/console
I replayed job 53606 (as 53607) with this new code, and it passed.
=> Hnadle the case where the deploy-username isn't set.

weekly-maintenance.sh
We used to use prod-read, but I think that account went away.  Now we
use the service account associated with the existing
gcloud-service-account.json file.
I hope (expect) this service account has all the permissions we need.
In general, we're not very good about limiting permissions for service
accounts.
Issue: none
Ran
```
make -C stackdriver ACCOUNT=stackdriver-service-account@khan-academy.iam.gserviceaccount.com
```
on jenkins-server in the webapp-maintenance job directory, and got no
access errors.
=> [🔥AUDIT🔥] Fix the gcloud account we try to run our network-config backups as.

jobs/e2e-test.groovy
notify-e2e-results.ts is ok with `--deployer` being missing, but
not with it being the empty string.
Issue: https://jenkins.khanacademy.org/job/deploy/job/e2e-test/53611/console
groovy jobs/e2e-test.groovy
=> [🔥AUDIT🔥] Do not pass the `--deployer` flag when no deployer is known.

weekly-maintenance.sh
I had activated a service-account in #169, but I didn't realize that
this command makes that service-account the default for all gcloud
operations.  We still want the default to be done as
prod-deploy@khanacademy.org!  And only use the service-account with
the `--account` flag.  This new command does that.
Issue: https://khanacademy.slack.com/archives/C096UP7D0/p1698352831330619
Ran the command manually on jenkins-server with success.
=> [🔥AUDIT🔥] Make sure jenkins-server runs as prod-deploy@.

weekly-maintenance.sh
The backup_network job was failing, but the script wasn't reporting
that it failed.  This is because a subshell exits with the result of
the lsat command, which in this case is an `echo` which always
suceeds.  Fix that.
Issue: https://jenkins.khanacademy.org/job/misc/job/webapp-maintenance/268/execution/node/910/log/
=> [🔥AUDIT🔥] Redo how we track failed jobs in weekly-maintenace.sh.

weekly-maintenance-jobs.sh
Sometimes the `gsutil ls <dir>` command lists the directory itself.  I
think that's a bug in gsutil -- it occurs in the gsutil installed with
gcloud 419, but not with gcloud 452 -- but it's easy enough to work
around it, so let's just do that.
Issue: https://jenkins.khanacademy.org/job/misc/job/webapp-maintenance/272/execution/node/264/log/
Ran the command manually with success.
=> [🔥AUDIT🔥] Work around a gsutil bug when cleaning ka-translations.

jobs/build-webapp.groovy, jobs/deploy-znd.groovy
We have enabled writing deploy metrics to stackdriver here https://github.com/Khan/webapp/pull/18161.  And that needs secrets so that alert lib can write to stackdriver. So that's what Im wiring on up in this audit.
Error message from jenkins logs:
```
13:15:03  Deployed service [recommendations] to [https://231120-1000-bfca1ab5c368-dot-recommendations-dot-khan-academy.appspot.com/]
13:15:03  
13:15:03  You can stream logs from the command line by running:
13:15:03    $ gcloud app logs tail -s recommendations
13:15:03  
13:15:03  To view your application in the web browser run:
13:15:03    $ gcloud app browse -s recommendations --project=khan-academy
13:15:03  [2023-11-20 18:15:00,815 INFO] Service recommendations version 231120-1000-bfca1ab5c368. Deployment …
```
=> [🔥AUDIT🔥] Secrets for alertlib in deploy to go script

jobs/update-devserver-static-images.groovy
Now that we're cross-compiling all our Go binaries on arm, using
emulation, it can take like 20 minutes to build the containers for a
single service.  So let's give it 10 hours to finish totally.
(A better solution is to use cross-compilation instead of emulation,
but that is a task for another day.)
Issue: none
=> [🔥AUDIT🔥] Let the update-devserver-images job take longer.  A lot longer.

vars/notify.groovy
I added some logic in https://github.com/Khan/jenkins-jobs/pull/181 to send a message to slack if a job was aborted while in a call to `sh` and `sh` never throws an exception that aborts the jenkins job.  In this follow up change I am making the check more precise to ensure the job is in the `ABORTED` state.
Issue: https://khanacademy.atlassian.net/browse/INFRA-9495
groovy vars/notify.groovy
=> [🔥AUDIT🔥] Add more precise abort check

jobs/update-devserver-static-images.groovy
The upload-images.sh script has been in master for a while now.
Issue: none
Will run this jenkins job manually.
=> [🔥AUDIT🔥] Just run upload-images.sh directly to upload images, rather than using make.

jobs/update-devserver-static-images.groovy
This jenkins job calls upload-images.sh a few dozen times, once for
each service.  By default, in each run upload-images.sh would create a
symlink-tag for all the services that are _not_ being deployed in that
run.  But we don't want a symlink-tag for those other services, since
they're going to be deployed for real in their turn, and will get a
real tag at that time.  Without this flag, the symlink-tags and real
tags will fight each other.
Issue: none
Will try running it.
=> [🔥AUDIT🔥] Pass the `--no-tags` flag to upload-images.sh.

jobs/deploy-webapp.groovy, jobs/deploy-webapp_slackmsgs.groovy
We have been slowly phasing out the infrastructure-devops channel and changing it to infrastructure-platform.  A couple of messages we send from jenkins reference the infrastructure-devops channel, so Im changing it to infrastructure-platform.
Issue: "none"
Wait for jenkins errors trying to communicate with buildmaster
=> [🔥AUDIT🔥] Changed infrastructure-devops channel to infrastructure-platform

jobs/e2e-test.groovy
This is a temporary measure while we investigate the cause of the slowness in
our e2e testing infra.
Verify that this replay worked as expected:
- First smoke test: https://jenkins.khanacademy.org/job/deploy/job/e2e-test/55630/console
=> Temporarily disable first smoke tests

jobs/e2e-test.groovy
After disabling the first smoke tests (#191), we've seen that the LambdaTest
infra is more stable. This gives us confidence that the first smoke tests are
back to how they were working before.
This PR reverts the change that skipped the first smoke tests and instead runs
the regular flow in the e2e-tests job.
N/A
=> Revert change that disabled first smoke tests

jobs/build-webapp.groovy, jobs/delete-version.groovy, jobs/deploy-webapp.groovy, jobs/deploy-znd.groovy, jobs/emergency-rollback.groovy, vars/onMaster.txt, vars/onWorker.txt, vars/withSecrets.groovy, vars/withSecrets.txt
Ever since https://github.com/Khan/webapp/pull/11178, Jenkins has not
deployed the dynamic (python2) service unless specifically asked to do
so via something like `sun: deploy mybranch (SERVICES=dynamic)`.  But
the code to deploy to default still existed.
This PR rips it out.  Way out!  Because the SAT service has been
sunset (sunsetted?), and there is no code running on these services
anymore.  If you ask to deploy the `dynamic` service you'll just get
an error.
This should wait until after 1 Jan 2024 to land, since that's when
the SAT product is formally sunset(ted).
Issue: https://khanacademy.atlassian.net/browse/INFRA-9701
=> Remove all references to deploying to GAE from the jenkins jobs.

vars/clean.groovy
This file is a special case: `third_party/__init__.py` used to be our
only contentful python init-file.  Then we deleted it.  But the .pyc
file isn't under git control, so it can only get deleted by a "clean"
call.  If we don't delete it, then it's still run whenever someone
imports something under third-party, which can cause trouble.  So now
we delete it even in the light-cleaning mode.
Issue: https://khanacademy.slack.com/archives/C096UP7D0/p1705697611608769?thread_ts=1705696301.913349&cid=C096UP7D0
groovy vars/clean.groovy
=> [🔥AUDIT🔥] Have jenkins-cleaning delete `third_party/__init__.pyc`.

jobs/e2e-test.groovy
This PR improves the e2e instrumentation by slightly changing the way we build
our e2e tests:
1. Adding tags to each spec, so we can easily filter them out in the future via
the Dashboard UI or the API.
2. Notifying to the #fei-testing-logs slack channel in case of "first/second
smoke test" failures.
Verify that the e2e tests are still running as expected and that the tags are
included in the test results.
=> Improve e2e instrumentation

jobs/build-webapp.groovy, jobs/delete-version.groovy, jobs/deploy-webapp.groovy, jobs/deploy-znd.groovy, jobs/emergency-rollback.groovy, jobs/find-failing-taskqueue-tasks.groovy, jobs/notify-znd-owners.groovy, jobs/update-ownership-data.groovy, jobs/webapp-test.groovy, vars/withVirtualenv.groovy, vars/withVirtualenv.txt
We are porting our deploy and testing scripts from python2 to python3.
Some of them need third-party libraries such as `requests` or
`graphql`, which we are supporting via a python3 virtualenv that is
constructed in webapp's deploy/Makefile.
This PR adds Jenkins support to use that virtualenv.  We don't have a
user-friendly way to enable the virtualenv -- we don't expect users to
run these scripts, just Jenkins -- but the new
`withVirtualenv.python3()` does all the needful.
I had a choice: I could set up this new virtualenv in onWorker() and
onMaster(), like we do with the python2 virtualenv, or I could require
jobs to call it manually to set it up in the places where it's needed.
I chose to do the latter, since our goal is to replace all our python3
with Go (or js) over time, and I'm …
=> Add support for enabling the python3 virtualenv when running jobs.

jobs/webapp-test.groovy
In #19440 I will be renaming the test-info files to be
test-info.db.json.  Let's change the webapp-test job to support both
naming formats.
Issue: https://khanacademy.atlassian.net/browse/INFRA-9702
Fingers crossed, will run tests on the `redo-timing-db` branch and
check jenkins-server:~jenkins/jobs/deploy/jobs/webapp-test/workspace
and see if test-info.db.json is there.
=> [🔥AUDIT🔥] Allow stashing and unstashing of test-info.db.json files.

jobs/e2e-test.groovy
The removed args don't do anything - they aren't passed along to the CLI invocation because we manage that stuff internally.
These are the args we support: https://github.com/Khan/webapp/blob/04b6b63ae70d1969427140601b0961e9540cb93f/services/static/dev/cypress/e2e/util/parse-lambdatest-arguments.ts#L34-L42
Related change for webapp GitHub actions: https://github.com/Khan/webapp/pull/19586
Issue: FEI-5354
There's nothing to test really - these args were already noops disappearing into the ether. However, on putting this change into rotation, we will see that all still works and nothing changed.
=> Remove args that just don't get used

jobs/make-allcheck.groovy, jobs/webapp-test.groovy
runtests-server.py ignores this, and has since I started the python2
deletion.  So let's not pretend it's meaningful.
We only have two large tests -- "large" because they talk to the
outside world, not because they take a long time -- so even if
MAX_SIZE was respected, it wouldn't really make any difference in
practice.
Issue: none
groovy jobs/webapp-tests.groovy
groovy jobs/make-allcheck.groovy
=> Get rid of the MAX_SIZE parameter in jenkins webapp-tests.

jobs/build-webapp.groovy, jobs/deploy-znd.groovy
As we transition to python3, we can't be sure which version to run,
from the groovy file.  Let's let the shebang line on the script tell
us.
That means we don't get `python -u` (unbuffered output) anymore, but I
don't think we need it anymore either.  At least, I hope...
Issue: https://jenkins.khanacademy.org/job/deploy/job/build-webapp/46494/execution/node/206/log/
=> [🔥AUDIT🔥] No longer call some python scripts with "python".

jobs/build-webapp.groovy
As we transition to python3, we can't be sure which version to run,
from the groovy file.  Let's let the shebang line on the script tell
us.
I tried to fix this in #202 but missed a case.
Issue: https://jenkins.khanacademy.org/job/deploy/job/build-webapp/46496/execution/node/425/log/
=> [🔥AUDIT🔥] Do not say "python" to run python binaries.

jobs/deploy-webapp.groovy, vars/notify.groovy
We have been getting for years an error that jenkins can't talk to buildmaster when running scheduled e2e tests.  The issue is that the e2e tests provide `master` as the git hash, which is good for jenkins to do its work.  But buildmaster only knows about hashes.  We have a check in place to ensure that when we provide something that is _NOT_ a hash, we don't talk to buildmaster.  But that's actually what Im fixing in these changes.
The errors we get in the request logs are actually not easy to find... https://console.cloud.google.com/logs/query;query=%22cdb93c4dfd5a826da095afe66dfec769%22;cursorTimestamp=2024-02-06T10:03:25.380529Z;aroundTime=2024-02-06T10:03:25.918112681Z;duration=PT30S?project=khan-internal-services
The copy of the trace in case you can't access the URL in the future. …
=> Fixed check if git shas are a branch name or not

vars/withVirtualenv.groovy
We are having issues with deployment script in jenkins setting up the virtual env.  While I look at the underlying issue, Im going to foce build the deps for the deployment scripts to get deployments up and running again.
Issue: https://khanacademy.slack.com/archives/C096UP7D0/p1707318372614619
I tested it by logging into a jenkins worker and verifying that `make -C webapp/deploy deps -B` runs successfully
=> [🔥AUDIT🔥] Force make deps for deploy scripts

vars/withVirtualenv.groovy
We're seeing pip at version 19 in the deploy (python3) virtualenv,
which shouldn't be happening!  We have an (unproven) theory that the
issue is that somehow our pip-downgrading is affecting that virtualenv
rather than the python2 virtualenv.  This PR should make that
impossible.
Issue: https://jenkins.khanacademy.org/job/deploy/job/build-webapp/lastFailedBuild/console
Fingers way crossed
=> When downgrading the pip, make sure we're downgrading the one in the virtualenv.

jobs/delete-version.groovy
The py3 virtualenv configs live inside webapp, so we need to make sure
the webapp repo is present before we can set the virtualenv up!
Issue: https://khanacademy.slack.com/archives/C096UP7D0/p1707504348171789
groovy jobs/delete-version.groovy
=> [🔥AUDIT🔥] Sync webapp before trying to load the python3 virtualenv

vars/onMaster.groovy, vars/onWorker.groovy
It seems like jenkins jobs on jenkins-server inherit their environment
from the java process, which is started by upstart and has a very
limited PATH.
`onMaster` updates PATH before running the user-job, but before this
PR it did it after doing some of its bookkeeping.  And it turns out
some of that bookkeeping needs the PATH to correctly access gcloud.
This PR sets the path before that bookkeeping, so the gcloud command
can succeed.
I've changed onWorker as well to be consistent.  In fact, I rearranged
some commands so they're consistent for both onWorker and onMaster.
(In not-meaningful ways, e..g putting `logNodeFinish` inside the
`timestamps` on both of them, instead of inside on one and outside on
the other.)
This fixes the problem that some gcloud calls would give errors, e.g. …
=> Set PATH up at the very beginning(ish) of `onMaster`.

jobs/webapp-maintenance.groovy
This change makes it so each failing task has a red dot next to it on
the pipeline-steps page.  Before this, they all had green dots, and
you had to look at the message at the end of the job to figure out
which tasks had failed.
(Now there is no message at the end of the job, which is maybe a
regression in quality but I think the red dots will be more useful.)
Issue: none
I manually re-ran this new code at
https://jenkins.khanacademy.org/job/misc/job/webapp-maintenance/293/console
=> Do a better job of indicating task failures in the weekly-maintenance script.

jobs/deploy-fastly.groovy
It looks like our deploy_fastly.py script needs to import third-party
libs, which means we need to use the virtualenv!  I just missed this
before because the jenkins jobs doesn't call a python script directly,
it calls a make rule that calls a python script.
Issue: https://khanacademy.slack.com/archives/CCCC6HZ4K/p1707924185156879
groovy jobs/deploy-fastly.groovy
Subscribers: @jandrade, @jeresig
=> [🔥AUDIT🔥] Make sure we run our fastly deploys with the python3 virtualenv.

jobs/notify-znd-owners.groovy, jobs/update-ownership-data.groovy
In #208 I fixed one jenkins job that was trying to activate the
python3 virtualenv before syncing webapp.  This could fail because the
py3 virtualenv configs live inside webapp, so we need to make sure the
webapp repo is present before we can set the virtualenv up!
I looked through all the jobs and these two are the only other ones
that need to be fixed up.
Issue: https://jenkins.khanacademy.org/job/misc/job/update-ownership-data/1752/execution/node/52/log/
groovy jobs/notify-znd-owners.groovy jobs/update-ownership-data.groovy
=> [🔥AUDIT🔥] Finish the job of syncing webapp before trying to load the virtualenv.

jobs/webapp-test.groovy
This replaces the call to the python2 version.  In theory they should
act identically.  We will see...
Issue: https://khanacademy.atlassian.net/browse/INFRA-9702
I ran this code with success, via "replay", at
https://jenkins.khanacademy.org/job/deploy/job/webapp-test/217277
=> Use the Go version of runtests-server!

jobs/deploy-webapp.groovy
In #208, and again in #212, I fixed jenkins jobs that were trying to
activate the python3 virtualenv before syncing webapp.  This could
fail because the py3 virtualenv configs live inside webapp, so we need
to make sure the webapp repo is present before we can set the
virtualenv up!
Well, it came up again.  This time it was more understandable, but
still.
Issue: https://khanacademy.slack.com/archives/C096UP7D0/p1708113113843639
grooyv jobs/deploy-webapp.groovy
=> [🔥AUDIT🔥] *Another* place we need to enable the virtualenv _after_ syncing webapp.

jobs/e2e-test.groovy
When running tests -- in this case smoketests -- there are two types
of failures.  The one you normally see is that a test fails, because
we wrote buggy code.  But it's also possible for the test framework
itself to fail: e.g. runlint.py fails to even run due to an import
error.
When running smoketests, we don't want the first type of failure --
actual failures to the smoketests -- to stop the deploy: we just want
to report them and let the deployer decide what to do.  But we do want
to have that second kind of failure stop the deploy, because it means
we don't even know what the smoketest results are!
This PR makes that change.  It depends on the fact that lambdatest
itself distinguishes between these two types of errors, and always
returns rc 0 on successful completion, even if there …
=> Fail if there are lambdatest framework failures.

weekly-maintenance-jobs.sh
This is going to run and that will cause the queryplanner and render-gateway services to attempt to deploy. However, the GCP node16 runtime is deprecated and those services can no longer be deployed. So we need to turn this off until we can successfully deploy this services again, hopefully next week.
Issue: FEI-5536
The weekly maintenance job should run without errors, I hope!
=> Turn off caniuse weekly upgrade, for now.

jobs/webapp-maintenance.groovy
When I moved to running the jobs one at a time, I stopped using the
runScripots() function, but it actually served an important purpose!
One we got away without for a while, but now the workspace has been
recreated and we need to sync webapp again.
Issue: https://jenkins.khanacademy.org/job/misc/job/webapp-maintenance/298/flowGraphTable/
Will run this job again.
=> [🔥AUDIT🔥] Actually sync webapp at the start of webapp-maintenance.groovy.

jobs/deploy-webapp.groovy
Slack is temporarily needed while should_deploy is doing side-by-side
testing of the go_code_analysis.go.
I only do this in deploy-webapp.groovy, though should_deploy.py is
also called in build_webapp.groovy, so we only get notified once per
deploy, not lots of times (as a deploy moves up the queue).  This not
only avoids spam, it makes it easier to figure out which deploy a
slack message corresponds to, since only one deploy-webapp job can be
running at a time.  Since both jobs give the same output, this is safe
to do.
Issue: none
groovy jobs/deploy-webapp.groovy
=> [🔥AUDIT🔥] Allow should_deploy.py to access slack when *deploying* to webapp.

jobs/deploy-webapp.groovy
We had a nasty issue sometime ago in this PR https://github.com/Khan/jenkins-jobs/issues/181.  I have since been able to confirm that the logic is correctly aborting the jobs so I am removing the messages we are sending to slack about stuck jobs.
Issue: https://khanacademy.slack.com/archives/C06385ANLAC/p1712855669448049
deploy and never see the message again :)
=> Removed debug slack message when deploys get stuck in jenkins

weekly-maintenance-jobs.sh
EDIT: I've updated this PR to use the official script (`update-browserslist-db`) instead of the manual `sed` + `yarn` system.
https://github.com/browserslist/update-db
~Our `weekly-maintenance-jobs.sh` script updates the browserslist and caniuse-lite packages. In the `yarn` invocation, we're using the wrong package name. Thankfully, there is a typo package (`browserlist`) that points to the right package. But long term we should be using the correct name (`browserslist` (note the `s` suffix)).~
~See: https://www.npmjs.com/package/browserlist which reads:~
~> Package to help in popular typo: browserlist instead of browserslist~
Issue: "none"
:fingerscrossed:
=> Use official update package/script for browserslist package update

safe_git.sh, weekly-maintenance-jobs.sh
Every so often -- very commonly when running the weekly maintenence gc
scripts, but at other times like `merge-branches` as well -- we see an
error like:
> warning: reflog of 'HEAD' references pruned commits
@Miguelcastillo did some sleuthing and found the fix, which I put
here.  Since every `pull` can cause a `gc`, I just clean the reflog
before every pull; we don't need the reflog in Jenkins, since it's
really a tool for manual git work and Jenkins is fully automated.
Issue: https://jenkins.khanacademy.org/job/misc/job/webapp-maintenance/316/execution/node/239/log/
I ran the new `git reflog` command manually on jenkins in
~jenkins/jobs/misc/jobs/webapp-maintenance/workspace/webapp,
and it ran ok.
=> Clean the reflog before pulling or gc-ing.

safe_git.sh
It's slow, and we believe it's causing errors (perhaps when the reflog
and gc coincide).
Issue: https://khanacademy.slack.com/archives/C096UP7D0/p1721248190898759
Subscribers: @somewhatabstract
=> [🔥AUDIT🔥] Do not do reflog cleaning all the time, only in the weekly maintenance.

jobs/update-devserver-static-images.groovy
In https://github.com/Khan/webapp/pull/24656, I change
upload-images.sh to use ssh-agent to register the ssh key.  This
actually runs ssh-agent on jenkins so we can make use of that.
Even before #24656 is landed, this is safe to do; it's just a noop.
Thus I'll do it first, then deploy the change in webapp.
Issue: https://khanacademy.slack.com/archives/C065UP1CC9M/p1723674135047609?thread_ts=1723667038.669609&cid=C065UP1CC9M
I ran this new script manually on jenkins:
https://jenkins.khanacademy.org/job/misc/job/update-devserver-static-images/395/console
Subscribers: @Khan/infra-platform
=> Run devserver's upload-images under ssh-agent.

jobs/update-ownership-data.groovy
When we update the ownership data in our nightly deploy, we run some
tests to make sure that the new ownership data doesn't break anything.
It turns out that some potential problems are tested in a _different_
ownership test, so we need to run that one too.
Issue: https://khanacademy.slack.com/archives/C02NMB1R5/p1724751059899299
I ran the new command manually on jenkins
Subscribers: @jeresig
=> [🔥AUDIT🔥] Run more ownership_data tests when updating ownership data.

jobs/build-webapp.groovy, jobs/deploy-webapp.groovy, jobs/deploy-znd.groovy
Several of our jobs run `virtualenv.withPython3` at a very high level
(in main).  And then call a function that calls `clean()`.
Unfortunately, that's not safe: `withPython3` builds python deps that
`clean()` can nuke.  Luckily, this doesn't happen by default: you have
to run with `CLEAN=all`.  But it's still a problem.
This PR refactors the jobs so they always run `withPython3` after
`clean`, rather than before.  A better fix would be to only run
`withPython3` in the places we're actually running python3 code, not
at this high level in `main()`, but that's a more significant
refactor, for another day.
Issue: https://khanacademy.slack.com/archives/C01120CNCS0/p1724860397897649
Mostly fingers crossed -- I'll try the jobs on Jenkins.  But I did run:
``` …
```
=> Refactor the jenkins jobs so they don't run `clean` after building deps.

jobs/update-devserver-static-images.groovy, jobs/update-ownership-data.groovy
That is what the `automated-commits` branch is for!  So let people
know that in the two jobs that push things to a user-specified branch.
Issue: https://khanacademy.slack.com/archives/C096UP7D0/p1726518628937639
groovy jobs/update-devserver-static-images.groovy
groovy jobs/update-ownership-data.groovy
Subscribers: @kevinb-khan
=> Do not allow pushing to webapp's master from jenkins jobs.

jobs/deploy-webapp.groovy
The idea is that if you are deploying fastly as part of your deploy,
we want the pre-set-default url
(`https://prod-2409<etc>.khanacademy.org`), to execute the new fastly
code.  The way we do this is to deploy the new fastly code to a
separate "staging" fastly service, and then route all requests to
prod-etc.ka.org to that staging fastly service instead of the regular
prod fastly service.
The details of how we do that routing are beyond the scope of this PR,
but this PR _does_ do the important step of making sure that the
"staging" fastly service has the code for this deploy in it!  And it
makes sure that happens before we do the "set default" prompt, so that
any manual testing that is done gets the new fastly.
Sadly, the first-smoke-test run does _not_ hit the new fastly, it
still hits …
=> Deploy to fastly-staging as part of the deploy process.

weekly-maintenance-jobs.sh
We got into an error when gc-ing this week:
```
+ echo 'GC-ing in /var/lib/jenkins/jobs/deploy/jobs/merge-branches/workspace@15/webapp'
GC-ing in /var/lib/jenkins/jobs/deploy/jobs/merge-branches/workspace@15/webapp
+ cd /var/lib/jenkins/jobs/deploy/jobs/merge-branches/workspace@15/webapp
+ git reflog expire --all --stale-fix
fatal: unable to parse object: refs/remotes/origin/AX-194
```
Perhaps because AX-194 got deleted, but this branch didn't get the
memo.  In any case, `git remote prune` is meant to handle exactly this
situation.
Issue: https://jenkins.khanacademy.org/job/misc/job/webapp-maintenance/329/execution/node/382/log/
I successfully ran this command manually in
/var/lib/jenkins/jobs/deploy/jobs/merge-branches/workspace@15/webapp
=> [🔥AUDIT🔥] Do more pruning of bad references when gc-ing.

jobs/emergency-rollback.groovy, jobs/update-devserver-static-images.groovy, jobs/update-ownership-data.groovy, vars/notify.groovy
Sometimes, we send slack messages to a busy or unattended channel,
because most of the time the information isn't that interesting.  But
sometimes it's only not interesting when it works as intended --
e.g. the nightly dev-images update.  But if it fails, we want to know
about it.
This PR introduces the concept of a "failure channel", which if
specified means that when a job fails, we send the slack message
twice: once to the normal channel, but a second time to the failure
channel.  The idea being the failure channel is looked at more
closely.
I use this concept for a few jobs I think would benefit from it:
emergency-rollback -- which has been broken since March and we never
really noticed! -- and the update scripts.
Issue: none
Fingers crossed.  I did run
```
groovy vars/notify.groovy …
```
=> Add the concept of a "failure channel" and use it for emergency-rollback.

vars/kaGit.groovy, weekly-maintenance-jobs.sh
We have 55,000 of these!  They were meant to be short-lived (like a
few minutes long) tags, but we never wrote the code to prune them.
Let's do that now.
Issue: https://khanacademy.slack.com/archives/C01120CNCS0/p1731094743406639
Fingers crossed.  I ran the grep part manually and saw it exclude tags
from the last 7 days.
=> Clean up the buildmaster tags every week.

jobs/e2e-test.groovy
We want to be able to easily run E2E jobs using different Fastly services.  This PR adds a new param to the E2E test job to support this.  It requires https://github.com/Khan/webapp/pull/27243 in order to work correctly.
Issue: None
- land this PR
- run the E2E tests on 'route-e2e-tests-to-compute' using 'PROD [Compute]' from the dropdown
=> Add FASTLY_SERVICE param to E2E test job

jobs/e2e-test.groovy
@miguelcastillo caught a mistake I made in #250.  I was passing the service ID instead of the cookie value.  This PR fixes that and adds a link to the Confluence page with the cookie values which is our source of truth for these values.
The corresponding webapp changes can be found in https://github.com/Khan/webapp/pull/27243.
Issue: None
- land
- start a job and stop it (this will force jenkins to update)
- start a new job that runs tests on the `route-e2e-tests-to-compute` branch in webapp and sets the `FASTLY_SERVICE` param to `PROD [Compute]`
=> [🔥AUDIT🔥] Pass FASTLY_COMPUTE_ENVIRONMENT_COOKIE to lambdatest

jobs/e2e-test.groovy
This PR makes the following fixes:
- updates the values for the cookies to be the actual cookies instead of service IDs
- modifies the '--envs' param we pass to lambdatest to use '--envs=' which lambdatest recognizes correctly
Issue: None
- land
- run a throwaway job
- run another job using the 'route-e2e-tests-to-compute' webapp branch
=> [🔥AUDIT🔥] Fix FASTLY_SERVICE param handling in E2E job

jobs/deploy-znd.groovy
We used to let people turn off translating all the js at deploy time,
if they only wanted to test language-agnostic functionality. This
made the deploys go quite a bit faster.
But now we no longer translate at deploy-time, but instead at runtime.
So there's no need for this option anymore!
I removed it in webapp in https://github.com/Khan/webapp/pull/27729.
I could have left it as a deprecated param here, but since we can just
tell people not to use `deploy_znd.py` with the `--no-i18n` flag
anymore, there's no need to keep it around, and it's nice to clean it
up.
In fact, I cleaned up another param we don't use anymore, MODULES.
Issue: https://khanacademy.slack.com/archives/C02NMB1R5/p1732547649381639
Mostly fingers crossed.  I did, however, visit …
=> Get rid of some unused parameters on the deploy-znd job.

jobs/e2e-test-cycloud.groovy
Adds a temporary jenkins job to run e2e tests on Cypress Cloud. This job will be
removed once the tests are running successfully on Cypress Cloud.
The goal is to use parallel workers in Jenkins directly to run concurrent
cypress processes. This will allow us evaluate the performance of the tests
and the feasibility of switching to Cypress Cloud.
NOTE: I used the previous `e2e-test.groovy` template as reference: https://github.com/Khan/jenkins-jobs/blob/fc496e120f19c439348ae4136a0f92c909b5ab2c/jobs/e2e-test.groovy
Make sure that the `CYPRESS_GIT_REVISION` parameter is set to the correct branch:
`cycloud-skipped`.
1. Run the job `e2e-test-cycloud` in Jenkins.
2. Verify that the tests are running on Cypress Cloud.
=> Add temporary Cypress Cloud integration

jobs/deploy-webapp.groovy
Proceed to confirm set default prompt when first E2E test is in the new
state "skipped", which is added in:
https://github.com/Khan/buildmaster2/pull/219
https://khanacademy.atlassian.net/wiki/spaces/ENG/pages/2643591176/ADR+699+Allow+for+less-attended+and+unattended+deploys#Speed
Issue: https://khanacademy.atlassian.net/browse/INFRA-9995
Test plan:
Before buildmaster changes deployed:
1. `sun: queue foo` in #1s-and-0s-deploys
2. Open queue dialog
3. Fill out dialog and select None for user-facing level.
4. Proceed with deployment.
6. Verify deployment was successful.
After buildmaster changes deployed:
1. `sun: queue foo` in #1s-and-0s-deploys
2. Open queue dialog
3. Fill out dialog and select user-facing for user-facing level.
4. Proceed with deployment.
5. Verify first e2e tests were …
=> Handle first E2E test skipped state

jobs/check-assessment-exercise-ids.groovy
Our interim assessments contain exercise IDs that we use to look up content, and we need to be alerted if any of those IDs become invalid. This job checks for invalid exercise IDs and alerts us if it finds any.
Issue: INFRA-10509
Verify that the job ran correctly [in Jenkins](https://jenkins.khanacademy.org/job/misc/job/check-assessment-exercise-ids/). Note that the failure is intended - I made a test configuration invalid to ensure the alert would work.
=> Add job to validate exercise IDs in assessments

jobs/build-webapp.groovy, jobs/deploy-znd.groovy
Now that we are routing to cloud-run in fastly (and Go), we no longer
need to create tags on every deploy to help us with the routing.  Huzzah!
This needs to wait to deploy until we are fully off of VCL and not
going back.  Since we did not backport the route-to-cloud-run logic to
VCL.
Issue: https://khanacademy.atlassian.net/browse/INFRA-10502
I ran `groovy jobs/build-webapp.groovy` without any new errors.
=> No longer create cloud-run tags on every deploy.

jobs/demo-district-update-pass.groovy, jobs/e2e-test-cycloud.groovy, jobs/e2e-test.groovy, weekly-maintenance-jobs.sh
This is a follow-up to:
https://github.com/Khan/webapp/pull/28829
I changed the few places where we install packages to use `make npm_deps` instead. The two places where we were calling a yarn script I now use the new shell script for this, instead. This is all in service of moving off of yarn v1 to pnpm v10 instead.
Issue: FEI-6143
Will need to deploy the webapp changes first. But I'm a bit unclear on how to best test this!
=> Don't call yarn directly in jenkins-jobs.

jobs/e2e-test.groovy
changed cycloud call in e2e-test to use the new one created in deploys `e2e-test-cycloud`
Issue: none
none
=> [🔥AUDIT🔥] change path of cycloud job now that it is added to deploy folder

jobs/e2e-test-cycloud.groovy
If e2e-test-cycloud finishes after e2e-test, it will overwrite both the
result and job ID.
This has been causing 2 bugs:
1. The link to the e2e job in jenkins points to e2e-test but with the
e2e-test-cycloud job id. Resulting in a dead link.
2. The status of the smoke test in buildmaster is failed when e2e-test
passes but e2e-test-cycloud fails.
Issue: https://khanacademy.slack.com/archives/C096UP7D0/p1740083704822279?thread_ts=1739930668.893529&cid=C096UP7D0
Monitor deployment queue.
=> Prevent e2e-test-cycloud from overwriting smoke test result in buildmaster

jobs/e2e-test-cycloud.groovy
use safePull instead of safePullInBranch due to rebase issue
safePullInBranch was causing an issue:
```
00:04:56.250  + _rebase a5ade2bbc577a327bb69c63ea97c6ce7c419688f
00:04:56.250  + timeout 10m git rebase origin/a5ade2bbc577a327bb69c63ea97c6ce7c419688f
00:04:56.250  fatal: invalid upstream 'origin/a5ade2bbc577a327bb69c63ea97c6ce7c419688f'
00:04:56.250  + timeout 10m git rebase --abort
00:04:56.250  fatal: No rebase in progress?
```
Issue: none
ran test on test job
=> use safePull instaed of safePullInBranch

jobs/e2e-test.groovy
generate skipped list once
add skip gen flag
unstash skipped list on each worker
Issue: FEI-6282
tested on debug jenkins job
=> Generate skipped list once to avoid google rate limiter

jobs/build-current-sqlite.groovy
We turned this off when we moved to goliath, because the local
datastore only has user data in it, and that doesn't change very
often.  But it turns out it does change sometimes -- the permissions
granted to testadmin grow over time as more permissions get added to
our system (since testadmin is supposed to have all permissions).  So
there's some value in updating this data periodically.  This new job
does just that.
Issue: https://khanacademy.slack.com/archives/C04SEFXQBNU/p1740171086452009
I went to
https://jenkins.khanacademy.org/job/misc/job/build-current-sqlite/1530/replay
and replaced the "Main Script" text with the new script text, except
for the addCronSchedule line, and ran it with success!
=> Get the build-current-sqlite script running again.

jobs/build-current-sqlite.groovy
When Docker Compose sees sees an envvar defined both in the
(shell) environment and in an `.env` file, the environment wins:
https://docs.docker.com/compose/how-tos/environment-variables/variable-interpolation/#ways-to-set-variables-with-interpolation
This means envvars that Jenkins sets can interfere with our running
Docker.  And this is indeed what happened.
Issue: https://jenkins.khanacademy.org/job/misc/job/build-current-sqlite/1535/console
Fingers crossed, will try again.
=> [🔥AUDIT🔥] Make sure Jenkink's BUILD_TAG var doesn't conflict with ours.

jobs/build-current-sqlite.groovy
This was causing an error:
```
15:00:32  make -C dev/server stop
15:00:32  make[1]: Entering directory '/home/ubuntu/webapp-workspace/webapp/dev/server'
15:00:32  docker compose \
15:00:32       -f docker-compose.all-modes.yml  -f docker-compose.backend.yml  -f docker-compose.frontend.yml  -f ../../genfiles/devserver/docker-compose.working-on.yml \
15:00:32      -p webapp \
15:00:32      --project-directory ../.. \
15:00:32      --env-file ../../genfiles/devserver/docker-compose.env \
15:00:32      down
15:00:32  time="2025-03-06T15:00:31-08:00" level=warning msg="The \"SSH_AUTH_SOCK\" variable is not set. Defaulting to a blank string."
15:00:32  time="2025-03-06T15:00:31-08:00" level=warning msg="The \"SSH_AUTH_SOCK\" variable is not set. Defaulting to a blank …
```
=> [🔥AUDIT🔥] We need an ssh-agent whenever we do docker stuff.

weekly-maintenance-jobs.sh
We're fully on pnpm now, and yarn.lock doesn't exist anymore.
Checking for it caused the job to fail.
Issue: https://jenkins.khanacademy.org/job/misc/job/webapp-maintenance/352/execution/node/1229/log/
Fingers crossed for next run.
=> Get rid of references to yarn.lock in our weekly-update script.

jobs/build-current-sqlite.groovy
It had a few problems:
1. It tried to delete the database file after starting the datastore
emulator.  That ain't gonna fly.  Instead, we have to depend on create_dev_users to properly delete old users before creating new ones (which it does).
2. I was using too many `gs://`'s in a row.
3. I was only putting the WEB_INF directory into the tar file, not all
the files that the datastore emulator creates.  This is problematic
because if not all the files are in the tarfile, the datastore
emulator will create them, and they will be owned by root, and we
won't be able to clean them up.
To bootstrap the solution to (3), I manually updated a new version of
dev_datastore.tar to gcs that has all the files in datastore/.  So
next time this script runs, it will populate datastore/ on the build …
=> Fix the build-current-sqlite script to actually work.

jobs/build-current-sqlite.groovy
It looks like the current datastore archive in GCS contains a previous version
of the archive[1]. This is because we download the previous version of the
archive into the same directory being archived. It looks like this change was
introduced in #285, and March 9th was the last day we successfully generated a
new archive.
This PR excludes the previous archive file when creating the new archive.
[1] https://khanacademy.slack.com/archives/C02NMB1R5/p1741838164634579?thread_ts=1741827828.632279&cid=C02NMB1R5
I downloaded the existing archive:
```
cd datastore
gsutil cp gs://ka_dev_sync/dev_datastore.tar .
```
and then ran:
```
tar --exclude dev_datastore.tar -C datastore -c . | tar tv
```
This shows that the archive created with the new --exclude flag indeed doesn't
create …
=> Do not include existing datastore archive in new datastore archives

jobs/deploy-fastly.groovy
In addition, I got rid of some help text that just reiterated the
values in the drop-down.
Issue: https://jenkins.khanacademy.org/job/deploy/job/deploy-fastly/2489/console
Will deploy again!
=> [🔥AUDIT🔥] Fix a typo in the SERVICE list in deploy-fastly.groovy.

jobs/e2e-test.groovy
re-added slack notifications from webapp script
currently, there is no tagged notification on e2e tests passing so deployers have missed the cue if they weren't paying super close attention
Issue: FEI-6290
ran script on jenkins test job
=> Re-added slack notifications from webapp script

jobs/deploy-fastly.groovy
We have a goal of posting to the `#whats-happening` slack channel
whenever we deploy a change to our production system.  Currently,
changes to our fastly configs are noticed, via polling, by a cronjob
running on toby.  But now that all fastly deploys are (supposed to) go
through this jenkins job, it can do the reporting to #whats-happening
instead!
Once this is live, I'll disable the toby cronjob.  Or rather, I'll
repurpose it to notice when deploys to fastly are made via the UI and
not via the fastly deploy process.
Issue: https://khanacademy.slack.com/archives/C06T4JE5HCN/p1741644811156629
Fingers crossed, we'll see what happens next time we need to deploy
prod vcl!
=> Post to `#whats-happening` when we deploy to fastly.

jobs/build-current-sqlite.groovy
Users were seeing issues where the current.sqlite that they downloaded
from gcs had a `testadmin` user without admin permissions.  I could
see from the jenkins logs that we were running the grant-permissions
script, and it was finishing successfully, so my best theory as to
what is going wrong is that those changes weren't being fully flushed
to disk before we copied the db file to gcs.
I now add a command that I _hope_ will cause such flushing to happen.
Sadly, I couldn't find a supported way to flush the db or even stop
it, so I'm hoping that `kill` does the right thing.  It has to, right?
Issue: https://khanacademy.slack.com/archives/C04SEFXQBNU/p1742583382311709?thread_ts=1742502207.930369&cid=C04SEFXQBNU
I ran this new script manually, using replay, at …
=> Make sure the datastore is synced to disk before copying it to gcs.

jobs/e2e-test.groovy
In e2e tests, we were only syncing webapp on the workers actually
running the tests.  But we need to do it on the "orchestrator" machine
too!
Issue: https://khanacademy.slack.com/archives/C01120CNCS0/p1742922725261679
Subscribers: @somewhatabstract
=> [🔥AUDIT🔥] Make sure to sync webapp when generating the skipped list too.

vars/withSecrets.groovy
Our jenkins jobs use alertlib to post to slack.  Alertlib uses the
bot-token of a particular slack-app that has permission to post
messages to all our channels.
Yesterday, slack disabled the slack-app we had been telling alertlib
to use, because it used a too-old app API.  But it turns out we have a
new, modern slack-app that can do the same thing!  So we just need to
tell alertlib to use that app instead.  This PR does that.
See https://khanacademy.slack.com/archives/C096UP7D0/p1743628787094999
Issue: https://khanacademy.atlassian.net/browse/INFRA-10596
Test plan:
Fingers crossed, I did try using this token locally and it
successfully posted to slack:
```
% echo testing-dist | env ALERTLIB_SECRETS_DIR=/var/tmp ./alert.py --slack=#bot-testing --icon-emoji=:jenkins: --chat-sender="Yo Yo …
```
=> Have alertlib post via a new slack-app.

.gitignore, fastly_notifier.py, jobs/deploy-fastly.groovy
All of our fastly services are intended to be deployed via the
fastly-deploy jenkins job.  However, sometimes people deploy a fastly
service manually, by going to the fastly UI, hitting "clone", making
some changes, and hitting "save".  We do not want such changes to
happen, since there is no record of them in source control, and indeed
the change will be overwritten the next time a "proper" deploy
happens, via fastly-deploy.
This new script notices when such deploys happen.  It works in concert
with the fastly-deploy job to do its work: fastly-deploy says what
versions it has deployed, and we talk to the fastly API to find out
what versions are live that were *not* deployed by fastly-deploy.
When we see one, we alert in an alerting channel, and also in
production system.
A similar script …
=> Notify when someone manually deploys a change to fastly.

jobs/deploy-fastly.groovy
I've moved the directory to its standard location inside webapp, so we
don't need to special-case it in this jenkins job anymore!
Issue: https://khanacademy.atlassian.net/browse/INFRA-10538
=> [🔥AUDIT🔥] Fix the service-dir for fastly-vcl.

jobs/deploy-znd.groovy
Now that fastly-ka-compute is deployed like any other service, the
deploy-znd is very happy to deploy it.  But we can't deploy a znd of
our fastly services!  At least not yet.  Let's specifically skip it.
This isn't strictly necessary: while deploy-znd deploys the fastly
service, it never calls set-default on it, so the deployment doesn't
do anything; it just sits there.  But it's wasted resources to build
it and then have it sit on fastly's servers, never to be used.
I don't know if it's better to just skip it and continue deploying, or
to fail the deploy.  For now I do the former; I think this situation
will most likely arise when someone is editing 'pkg' and selects
"AUTO" for services, in which case they weren't expecting to update
fastly as part of their znd deploy in any case. …
=> Do not deploy to fastly-khanacademy-compute in deploy-znd.

jobs/deploy-webapp.groovy, jobs/emergency-rollback.groovy
When we change the default version of our backend services, we tell
slack, but we also tell stackdriver so we have monitorable stats about
it.  (Though I'm not sure anyone looks at them, which is good given
what I'm about to say.)  We correctly decrypt the necessary
stackdriver secret during a normal deploy, but forget to do so during
rollback.  This means that none of our rollback activity has been
recorded in stackdriver for probably a year now.
Issue: https://khanacademy.slack.com/archives/C096UP7D0/p1744158543865099?thread_ts=1744157711.877779&cid=C096UP7D0
=> Decrypt stackdriver secrets for rollback.

jobs/deploy-fastly.groovy
I don't know why I was sending the message to #fastly instead.  That
channel already gets plenty of updates while a fastly deploy is
happening.
Issue: https://khanacademy.slack.com/archives/CCCC6HZ4K/p1744413054178629
=> [🔥AUDIT🔥] Alert to #whats-happening like we said we were going to, on fastly deploys.

jobs/build-webapp.groovy
We are seeing rspack hang at this point:
```
13:47:58  > [3/4] Optimize modules
13:47:58  	[70%] sealing - finish modules
```
https://jenkins.khanacademy.org/job/deploy/job/build-webapp/62204/console
In previous investigations, this was determined to be caused by running
out of memory. Bumping the memory for the node process fixed this for
local dev. We tried bumping this even higher for jenkins but saw little
to no reduction in intermittent hanging builds.
https://github.com/Khan/webapp/pull/31069
This node process is competing for memory with all the other service
deploys currently run in parallel. Change static build and deploy to run
by itself to avoid the node process running out of memory. If folks are
separating their front and back end deploys, this shouldn't slow down
builds. …
=> Run static build and deploy by itself

vars/withSecrets.groovy
They both have the same value, but the new name is more desciptive.
Issue: https://github.com/Khan/aws-config/pull/149#discussion_r2059178438
I used "replay" to deploy to fastly-test with this new withSecrets code:
https://jenkins.khanacademy.org/job/deploy/job/deploy-fastly/2563/console
=> [🔥AUDIT🔥] Rename districts_slack_secret to alertlib_slack_secret.

jobs/deploy-znd.groovy
We are having an issue where updates to queries in from manually created znds are failing to pass our safelisting checks in the graphql gateway, which causes requests from znds to fail.  This regressed when we updated how we check for permissions of safelisted queries some time ago.
So in this PR I am making sure that we are adding queries from znds that engineers create themselves via jenkins. What Im not doing however, is priming queryplanner caches since these types of znds usually don't need to pre create all the queryplans as engineers tend to use a small subset of the UI.
I found this when I was testing adding the x-trace header to tasks we queue from our backends, which can be seen here https://cloudlogging.app.goo.gl/sHnpaBj8Fke8myCp7.
Issue: INFRA-10640 …
=> Update the graphql safelist when we deploy znds

jobs/build-webapp.groovy, jobs/deploy-znd.groovy
We want to disallow deploying frontend and backend changes together (in general and in preperation for moving the frontend code out into a new repo).
We're not going to deploy this until we're absolutely sure that we've figured out any edge cases, but it's likely that we're really close to deploying this.
All the changes we've made are in these two epics:
https://khanacademy.atlassian.net/browse/FEI-6194
https://khanacademy.atlassian.net/browse/FEI-6178
Issue: FEI-6189
Not sure how to test this... I think this is syntactically correct, but I assume the test plan is probably deploying this and then confirming that a plain static (or non-static) deploy continues to work - and that a combination deploy correctly fails.
=> [FEI-6189] Disallow deploying frontend and backend changes at the same time.

weekly-maintenance-jobs.sh
The old method updated package.json.  Worse, it updated packages
unrelated to caniuse, which is scary to do in an automated fashion.
We tried to fix this in https://github.com/Khan/webapp/pull/30986 but
it looks like that fix wasn't sufficient.  Luckily, @jeresig found a
different fix!
Issue: https://khanacademy.slack.com/archives/CEA6W0F6F/p1747670426392169
I ran the script manually:
```
for d in `git grep -l caniuse-lite "*pnpm-lock.yaml" | xargs -n1 dirname`; do
(
cd "$d"
pnpm up caniuse-lite --no-save
)
done
```
I then ran `git status` and saw only pnpm-lock.yaml files were modified.
I ran `git diff` and saw that for many repos, only the caniuse entries
were modified in the lockfile.  But in some repos, there were other
modifications, e.g. in services/static/pnpm-lock.yaml I saw:
``` …
```
=> Use a new, more reliable, script for updating the caniuse node deps.

vars/kaGit.groovy
We call resolveCommitish() whenever someone enters a git commit to run
a jenkins job.  It turns a branch or tag into a sha.  But it turns out
the command it uses, `ls-remote` doesn't do exact matches: if you
search for `john` it will return both `refs/head/john` and
`refs/head/deploy/john`.  This has been causing problems where folks
look to deploy one branch and end up deploying a different one.
I fix this here by looking for the *smallest* match.  That is the most
exact one; everything else has another component in it which makes it
a not-exact match.
This isn't perfect, if you had two branches called `foo/suffix` and
`bar/suffix` and tried to deploy `suffix`, it would deploy
`foo/suffix` rather than giving an error that the branch `suffix`
doesn't exist.  But that doesn't happen for us …
=> Fix resolveCommitish to work on ambiguous refs.

jobs/deploy-buildmaster.groovy
We are working on splitting up the FE code out of the webapp repo and implement its own deploy system.  And we need to be able to deploy to buildmaster from a branch that is not master!  So we are making a change in jenkins to enable that temporarily and we will revert this as soon as we are done this weekend.
Issue: https://khanacademy.slack.com/archives/C01120CNCS0/p1749233546013349
we are going to deploy these changes and retry deploying to buildmaster
=> [🔥AUDIT🔥] Enable the ability to deploy non master branches to buildmaster

vars/kaGit.groovy
We fixed an issue previously in https://github.com/Khan/jenkins-jobs/pull/336 where resolving commit hashes to branch names was incorrect.  That PR fixed the underlying issue, but the sorting code is not correct.  It is an issue specifically with groovy in jenkins. The error looks like:
```
at PluginClassLoader for script-security//org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetArray(SandboxInterceptor.java:482)
at PluginClassLoader for script-security//org.kohsuke.groovy.sandbox.impl.Checker$11.call(Checker.java:509)
at PluginClassLoader for script-security//org.kohsuke.groovy.sandbox.impl.Checker.checkedGetArray(Checker.java:514)
at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.sandbox.SandboxInvoker.getArray(SandboxInvo …
```
=> [🔥AUDIT🔥] Fix sorting list of string in jenkins groovy

jobs/deploy-znd.groovy
We have a new employee whose usename includes an underscore, and they
couldn't deploy a znd because the version-name we constructed, which
includes their username, had an underscore and google doesn't like
that.
We already had code to handle periods in usernames, this PR extends
that to all "bad" hostname characters.
Issue: https://khanacademy.slack.com/archives/CDHPTMSTB/p1750190468735759
I ran this new code manually via `replay` at
https://jenkins.khanacademy.org/job/deploy/job/deploy-znd/11390/console
just far enough to have it run my changed code.  And it emitted:
```
Failure message: Version: znd-250708-csilvers-strk
```
which shows it's calculating the version correctly still!
Subscribers: @johnyojohn
=> Have deploy-znd work if a username has non-alnums in it.

jobs/build-current-sqlite.groovy
Now we need both khan/webapp and khan/frontend to run the local
devserver, which was causing the current-sqlite job to fail since it
only synced webapp.  This fixes that.
To get this to work, I had to manually run:
```
timeout 60m git clone git@github.com:Khan/frontend /var/lib/jenkins/repositories/frontend
```
on jenkins-server as the jenkins user.  The script tried to run it (in
https://jenkins.khanacademy.org/job/misc/job/build-current-sqlite/1565/console)
but it failed with an EPERM error, I don't know why.
Issue: https://jenkins.khanacademy.org/job/misc/job/build-current-sqlite/1564/console
I ran the new commands manually via `replay` at
https://jenkins.khanacademy.org/job/misc/job/build-current-sqlite/1568/console
=> Fix the build-current-sqlite job by syncing the frontend repo.

jobs/deploy-znd.groovy, jobs/merge-branches.groovy, vars/exec.groovy, vars/kaGit.groovy, vars/notify.groovy
Include failure reason and stack trace when sending failure
notifications to slack.
Add sh wrapper that allows collection of stderr, stdout and exit code.
For merge-branches, include the output of the `git checkout` and
`git merge` commands.
This is the start of an ongoing effort to push the reason for Jenkins
job failures to the deployer via slack with a primary goal of reducing
the volume of @deploy-support-backend requests.  Right now, we direct
users to "look for the red circle(s)" in Jenkins which is fraught with
unrelated information that look like errors to anyone without intimate
knowledge of the deploy system. Ideally, users would never need to go to
Jenkins to know why their deployment failed and what actions they need
to take.
Some context on the motivations for doing so can be …
=> Propagate merge-branches errors to slack.

vars/kaGit.groovy
I completed a TODO in https://github.com/Khan/jenkins-jobs/pull/349 to
just have `kaGit.mergeRevisions` return the SHA from ls-remote if there
are actually no merges to perform. But by skipping checkout, 
`make gae_version_name` is generating the name from whatever 
cached version of the repo it had from the last job. This is preventing
the prerequisite merge-branches from successfully reporting back to 
buildmaster due to:
```
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "commit_gae_version_name_key"
```
So, webapp-test is never kicked off for PRs.
https://khanacademy.slack.com/archives/C013ANU53LK/p1755118117498589
Remove this optimization so that, when the merge-branches job calls
`make gae_version_name`, it is run against the correct git revision. …
=> Always perform a checkout during merge-branches

jobs/deploy-znd.groovy, jobs/merge-branches.groovy, vars/kaGit.groovy
Once developers started using `deploy/foo` as well as `foo` for branch
names, we found that the ls-remote logic was incorrectly returning
`deploy/foo` for `foo` when the name occured alphabetically after
`deploy`. We fixed that with the following PRs:
- https://github.com/Khan/jenkins-jobs/pull/336
- https://github.com/Khan/jenkins-jobs/pull/338
- https://github.com/Khan/jenkins-jobs/pull/339
However, we ran into a case where the new logic falls short. Here the
merge-branches job ended up picking `refs/tags/dbraley` over
`ref/heads/dbraley` due to being 1 character shorter.
https://khanacademy.slack.com/archives/C096UP7D0/p1753811466320829?thread_ts=1753811081.432949&cid=C096UP7D0
To fix this, only accept branch or tag names that are exact matches to
the commit-ish, preferring branches …
=> Find exact match for commit-ish, preferring branches over tags

jobs/e2e-test.groovy
Buildmaster hasn't sent this in a while, we can remove it from the
jenkins side as well.
Issue: https://khanacademy.atlassian.net/browse/INFRA-10563
Subscribers: @Khan/infra-platform
=> Get rid of the SKIP_TESTS parameter in our e2e tests.
